# -*- coding: utf-8 -*-
"""Another copy of TAB 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tH1itqKwWLbGxuzAWuYXR6aGae6RvaKR
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

folder_path = r'/content/'
# 1. Load Data
fact_video = pd.read_csv(f'{folder_path}Fact_Video.csv')
fact_monthly = pd.read_csv(f'{folder_path}Fact_Monthly.csv')
fact_channel_publishing = pd.read_csv(f'{folder_path}Fact_Channel_Publishing.csv')
fact_user_summary = pd.read_csv(f'{folder_path}Fact_User_Summary.csv')
fact_input_type = pd.read_csv(f'{folder_path}Fact_Input_Type.csv')
fact_output_type = pd.read_csv(f'{folder_path}Fact_Output_Type.csv')

# Load dimension tables
try:
    dim_user = pd.read_csv(f'{folder_path}Dim_User.csv')
    dim_channel = pd.read_csv(f'{folder_path}Dim_Channel.csv')
    dim_platform = pd.read_csv(f'{folder_path}Dim_Platform.csv')
    dim_input = pd.read_csv(f'{folder_path}Dim_Input_Type.csv')
    dim_output = pd.read_csv(f'{folder_path}Dim_Output_Type.csv')
    dim_month = pd.read_csv(f'{folder_path}Dim_Month.csv')
except Exception as e:
    print(f'Error loading a dimension table: {e}')

# Clean duration columns function
def duration_to_seconds(time_str):
    if pd.isna(time_str) or time_str == 0 or time_str == '0':
        return 0
    try:
        parts = str(time_str).split(':')
        if len(parts) == 3:
            return int(parts[0]) * 3600 + int(parts[1]) * 60 + int(float(parts[2]))
        elif len(parts) == 2:
            return int(parts[0]) * 60 + int(float(parts[1]))
        return 0
    except:
        return 0

for col in ['Total Uploaded Duration', 'Total Created Duration', 'Total Published Duration']:
    if col in fact_monthly.columns:
        fact_monthly[f'{col}_sec'] = fact_monthly[col].apply(duration_to_seconds)

print('Data loading and basic formatting complete.')

try:
    merged_user = pd.merge(fact_user_summary, dim_user, on='User_ID', how='left')
    if 'Uploaded Count' in merged_user.columns:
        top_users = merged_user.sort_values('Uploaded Count', ascending=False).head(10)
        plt.figure(figsize=(10,5))
        sns.barplot(data=top_users, x='Uploaded Count', y='User_Name', palette='viridis', hue='User_Name', dodge=False)
        plt.legend([],[], frameon=False) # remove redundant legend
        plt.title('Top 10 Users by Uploaded Count')
        plt.tight_layout()
        plt.show()
except Exception as e:
    print(f'Error plotting User Analysis: {e}')

"""10.USER REPATBILTY"""

import pandas as pd
import matplotlib.pyplot as plt

# 1. Load the user summary data
df = pd.read_csv('Fact_User_Summary.csv')

# 2. Basic Metrics
total_users = len(df)
# Users who uploaded exactly once
single_upload_users = df[df['Uploaded Count'] == 1]
# Users who uploaded more than once (Repeat Users)
repeat_users = df[df['Uploaded Count'] > 1]

num_single = len(single_upload_users)
num_repeat = len(repeat_users)

# 3. Calculate Repeatability Rate (%)
# Formula: (Repeat Users / Total Users) * 100
repeatability_rate = (num_repeat / total_users) * 100

print(f"Total Users: {total_users}")
print(f"Single-Upload Users (One-Timers): {num_single}")
print(f"Repeat Users: {num_repeat}")
print(f"User Repeatability Rate: {repeatability_rate:.2f}%")

# 4. Deep Dive: Loyalty Tiers
def categorize_loyalty(count):
    if count == 1: return "1. One-Timer"
    if 2 <= count <= 10: return "2. Regular (2-10)"
    if 11 <= count <= 50: return "3. Active (11-50)"
    if 51 <= count <= 100: return "4. Frequent (51-100)"
    return "5. Power User (100+)"

df['Loyalty_Tier'] = df['Uploaded Count'].apply(categorize_loyalty)
tier_distribution = df['Loyalty_Tier'].value_counts().sort_index()

# 5. Visualization
plt.figure(figsize=(10, 6))
tier_distribution.plot(kind='bar', color='skyblue', edgecolor='navy')
plt.title('User Repeatability: Distribution by Loyalty Tiers', fontsize=14, fontweight='bold')
plt.xlabel('Loyalty Tier (Number of Uploads)', fontsize=12)
plt.ylabel('Number of Users', fontsize=12)
plt.xticks(rotation=45)

for i, v in enumerate(tier_distribution):
    plt.text(i, v + 0.2, str(v), ha='center', fontweight='bold')

plt.tight_layout()
plt.savefig('user_repeatability_report.png')
plt.show()

# 6. Export for further use
df[['User_ID', 'Uploaded Count', 'Loyalty_Tier']].to_csv('User_Repeatability_Detail.csv', index=False)

"""Uploaded vs publised scatter"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# 1. Load the data
df = pd.read_csv('Fact_User_Summary.csv')

# 2. Setup Plot
plt.figure(figsize=(12, 8))

# 3. Create Scatter Plot
# X = Uploaded (Input Effort), Y = Published (Success Output)
plt.scatter(df['Uploaded Count'], df['Published Count'],
            alpha=0.6, s=100, c='#3498db', edgecolors='black')

# 4. Add Efficiency Trend Line
z = np.polyfit(df['Uploaded Count'], df['Published Count'], 1)
p = np.poly1d(z)
plt.plot(df['Uploaded Count'], p(df['Uploaded Count']), "r--", alpha=0.5, label='Avg Efficiency')

# 5. Labels and Styling
plt.title('User Activity Distribution: Uploaded vs. Published', fontsize=14, fontweight='bold')
plt.xlabel('Uploaded Count (Volume of Effort)', fontsize=12)
plt.ylabel('Published Count (Success Output)', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend()

plt.tight_layout()
plt.savefig('user_activity_distribution_scatter.png')

# --- ADD THIS TO THE BOTTOM OF YOUR CODE ---

# 1. Print the first 20 rows of the matrix to the console
print("\n--- CHANNEL > USER DRILL-DOWN MATRIX ---")
print(drill_down_matrix.head(20).to_string(index=False))

# 2. Print a summary count to verify data exists
print(f"\nTotal Rows Generated: {len(drill_down_matrix)}")
print(f"File Saved As: Channel_User_Drilldown_Matrix.csv")

"""from here Top 12 users publish rate
User Leaderboard
User per channel  Channel Publish rate   Channel creation efficiency   -
"""

import pandas as pd
import matplotlib.pyplot as plt

# 1. Load the data
df_user = pd.read_csv('Fact_User_Summary.csv')
df_user_channel = pd.read_csv('Fact_User_Channel.csv')
df_dim_channel = pd.read_csv('Dim_Channel.csv')
df_dim_user = pd.read_csv('Dim_User.csv') # Load Dim_User.csv

# Merge df_user with df_dim_user to get User_Name
df_user = pd.merge(df_user, df_dim_user, on='User_ID', how='left') # Merge here

# --- SECTION 1: USER METRICS ---

# KPI: Total Users
total_users_count = df_user['User_ID'].nunique()

# KPI: Top 12 Users Publish Rate
# Formula: (Published / Created) * 100
df_user['Publish_Rate_%'] = (df_user['Published Count'] / df_user['Created Count'] * 100).fillna(0)
top_12_publishers = df_user.sort_values(by='Publish_Rate_%', ascending=False).head(12)

# KPI: User Leaderboard
# Sorted by Published Count (Actual Success Output)
user_leaderboard = df_user[['User_Name', 'Uploaded Count', 'Published Count', 'Publish_Rate_%']].sort_values(by='Published Count', ascending=False)

# --- SECTION 2: CHANNEL METRICS ---

# Merge Channel data
df_channel_full = pd.merge(df_user_channel, df_dim_channel, on='Channel_ID')

# KPI: Users per Channel
users_per_channel = df_channel_full.groupby('Channel_Name')['User_ID'].nunique().reset_index(name='User_Count')

# KPI: Channel Performance (Publish Rate & Creation Efficiency)
# Creation Efficiency = (Created / Uploaded)
channel_performance = df_channel_full.groupby('Channel_Name').agg({
    'Uploaded Count': 'sum',
    'Created Count': 'sum',
    'Published Count': 'sum'
}).reset_index()

channel_performance['Channel_Publish_Rate_%'] = (channel_performance['Published Count'] / channel_performance['Created Count'] * 100).fillna(0)
channel_performance['Channel_Creation_Efficiency_%'] = (channel_performance['Created Count'] / channel_performance['Uploaded Count'] * 100).fillna(0)

# --- OUTPUT RESULTS ---

print(f"TOTAL REGISTERED USERS: {total_users_count}\n")

print("--- TOP 12 USERS BY PUBLISH RATE ---")
print(top_12_publishers[['User_Name', 'Publish_Rate_%']].to_string(index=False))

print("\n--- CHANNEL PERFORMANCE MATRIX ---")
print(channel_performance[['Channel_Name', 'Channel_Publish_Rate_%', 'Channel_Creation_Efficiency_%']].to_string(index=False))

# Optional: Visualization of Top 12 Publish Rates
plt.figure(figsize=(10, 6))
plt.bar(top_12_publishers['User_Name'], top_12_publishers['Publish_Rate_%'], color='#9b59b6')
plt.title('Top 12 Users: Publish Rate (%)', fontweight='bold')
plt.xticks(rotation=45)
plt.ylabel('Rate (%)')
plt.tight_layout()
plt.savefig('top_12_publish_rate.png')

"""Channel creation efficiency"""

import pandas as pd
import matplotlib.pyplot as plt

# 1. Load the data
# Fact_User_Channel contains the raw counts per user/channel
# Dim_Channel contains the human-readable names
df_fact = pd.read_csv('Fact_User_Channel.csv')
df_dim = pd.read_csv('Dim_Channel.csv')

# 2. Merge to get Channel Names
df = pd.merge(df_fact, df_dim, on='Channel_ID')

# 3. Aggregate at the Channel Level
channel_stats = df.groupby('Channel_Name').agg({
    'Uploaded Count': 'sum',
    'Created Count': 'sum'
}).reset_index()

# 4. KPI Formula: Creation Efficiency
# Efficiency = (Created / Uploaded) * 100
channel_stats['Creation_Efficiency_%'] = (channel_stats['Created Count'] / channel_stats['Uploaded Count'] * 100).fillna(0)

# Sort by efficiency to see top performers
channel_stats = channel_stats.sort_values(by='Creation_Efficiency_%', ascending=False)

# 5. Visualization
plt.figure(figsize=(12, 6))
bars = plt.bar(channel_stats['Channel_Name'], channel_stats['Creation_Efficiency_%'], color='#2ecc71', edgecolor='black')

plt.title('Channel Creation Efficiency (Clips Created per Upload)', fontsize=14, fontweight='bold')
plt.ylabel('Efficiency (%)')
plt.xticks(rotation=45)
plt.axhline(100, color='red', linestyle='--', label='1:1 Parity Line') # 100% baseline

# Add data labels
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 5, f'{yval:.1f}%', ha='center', fontweight='bold')

plt.legend()
plt.tight_layout()
plt.savefig('channel_creation_efficiency.png')

# 6. Output the raw matrix
print("--- CHANNEL CREATION EFFICIENCY MATRIX ---")
print(channel_stats[['Channel_Name', 'Uploaded Count', 'Created Count', 'Creation_Efficiency_%']].to_string(index=False))

"""Distribution of users per channels"""

import pandas as pd
import matplotlib.pyplot as plt

# 1. Load the relationship and dimension files
# Fact_User_Channel links User_IDs to Channel_IDs
# Dim_Channel provides the readable names for the channels
df_mapping = pd.read_csv('Fact_User_Channel.csv')
df_dim_channel = pd.read_csv('Dim_Channel.csv')

# 2. Merge to get Channel Names
df_merged = pd.merge(df_mapping, df_dim_channel, on='Channel_ID')

# 3. Aggregate: Count unique users per channel
users_per_channel = df_merged.groupby('Channel_Name')['User_ID'].nunique().reset_index()
users_per_channel.columns = ['Channel_Name', 'User_Count']

# Sort for a cleaner plot
users_per_channel = users_per_channel.sort_values(by='User_Count', ascending=False)

# 4. Visualization: Bar Chart
plt.figure(figsize=(10, 6))
bars = plt.bar(users_per_channel['Channel_Name'], users_per_channel['User_Count'],
               color='#9b59b6', edgecolor='black')

plt.title('Distribution of Users per Channel', fontsize=14, fontweight='bold')
plt.xlabel('Channel Name')
plt.ylabel('Number of Active Users')
plt.xticks(rotation=45)

# Add exact counts on top of each bar
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 0.1, f'{int(yval)}',
             ha='center', va='bottom', fontweight='bold')

plt.tight_layout()
plt.savefig('users_per_channel_plot.png')

# 5. Output Data Table
print("--- USERS PER CHANNEL DATA ---")
print(users_per_channel.to_string(index=False))

"""channel publishe rate"""

import pandas as pd
import matplotlib.pyplot as plt

# 1. Load the data
folder_path = r'/content/'
dim_channel = pd.read_csv(f'{folder_path}Dim_Channel.csv')
fact_user_channel = pd.read_csv(f'{folder_path}Fact_User_Channel.csv')

# 2. Aggregate Uploaded and Published Count by Channel_ID
channel_stats = fact_user_channel.groupby('Channel_ID').agg(
    {'Uploaded Count': 'sum', 'Published Count': 'sum'}
).reset_index()

# 3. Merge with Dim_Channel to get Channel Name
channel_stats = pd.merge(channel_stats, dim_channel, on='Channel_ID')

# 4. Calculate Publish Rate
# Publish Rate = (Published Videos / Uploaded Videos) * 100
channel_stats['Publish_Rate'] = (channel_stats['Published Count'] / channel_stats['Uploaded Count']) * 100

# Handle potential division by zero (if a channel has 0 uploads)
channel_stats['Publish_Rate'] = channel_stats['Publish_Rate'].fillna(0)

# 5. Sort by Publish Rate in descending order for better visualization
channel_stats = channel_stats.sort_values(by='Publish_Rate', ascending=False)

# 6. Visualization: Bar Chart
plt.figure(figsize=(12, 6))
bars = plt.bar(channel_stats['Channel_Name'], channel_stats['Publish_Rate'], color='#2ecc71', edgecolor='#27ae60')

plt.title('Channel Publish Rate (Published Videos / Uploaded Videos)', fontsize=14, fontweight='bold')
plt.xlabel('Channel Name', fontsize=12)
plt.ylabel('Publish Rate (%)', fontsize=12)
plt.xticks(rotation=45)

# Dynamically set y-axis limit to provide space for labels
max_publish_rate = channel_stats['Publish_Rate'].max()
if max_publish_rate > 0:
    plt.ylim(0, max_publish_rate * 1.15) # Add 15% padding above max bar

# Add data labels on top of bars, with relative positioning
for bar in bars:
    yval = bar.get_height()
    if yval > 0:
        plt.text(bar.get_x() + bar.get_width()/2, yval * 1.02, f'{yval:.1f}%', ha='center', va='bottom', fontweight='bold')

plt.tight_layout()
plt.savefig('channel_publish_rate.png')
plt.show()

"""user analysis header"""

import pandas as pd
import numpy as np

# 1. Load the real user data
df = pd.read_csv('Fact_User_Summary.csv')

# --- SECTION 1: TOTAL & ACTIVE USERS ---
total_users = len(df)
# Active Users (Repeat Users) = Users with more than 1 upload
repeat_users = len(df[df['Uploaded Count'] > 1])
repeatability_rate = (repeat_users / total_users) * 100

# --- SECTION 2: VOLUME METRICS ---
avg_uploads = df['Uploaded Count'].mean()

# --- SECTION 3: TOP 10% CONTRIBUTION ---
# Sort by success (Published Count) to find power users
df_sorted = df.sort_values(by='Published Count', ascending=False)
total_published = df['Published Count'].sum()

# Identify top 10% (by user count)
top_10_limit = max(1, int(np.ceil(0.10 * total_users)))
top_10_users = df_sorted.head(top_10_limit)
top_10_published = top_10_users['Published Count'].sum()

top_10_contribution_pct = (top_10_published / total_published) * 100

# --- OUTPUT: KPI SUMMARY TABLE ---
kpi_summary = pd.DataFrame({
    'Metric': [
        'Total Number of Users',
        'Active Users (Repeat Users)',
        'Repeatability Rate (%)',
        'Average Uploads per User',
        'Top 10% Contribution (%)'
    ],
    'Value': [
        total_users,
        repeat_users,
        f"{repeatability_rate:.1f}%",
        f"{avg_uploads:.2f}",
        f"{top_10_contribution_pct:.1f}%"
    ]
})

print(kpi_summary.to_string(index=False))
kpi_summary.to_csv('Executive_KPI_Summary.csv', index=False)

"""Channel analysis header"""

import pandas as pd
import matplotlib.pyplot as plt

# 1. Load your Channel Data
df_fact = pd.read_csv('Fact_User_Channel.csv')
df_dim = pd.read_csv('Dim_Channel.csv')
df = pd.merge(df_fact, df_dim, on='Channel_ID')

# 2. Aggregate Metrics at the Channel Level
channel_stats = df.groupby('Channel_Name').agg({
    'Uploaded Count': 'sum',
    'Created Count': 'sum',
    'Published Count': 'sum'
}).reset_index()

# 3. Calculate Efficiency & Rates
channel_stats['Creation_Efficiency'] = (channel_stats['Created Count'] / channel_stats['Uploaded Count']).fillna(0)
channel_stats['Publish_Rate_%'] = (channel_stats['Published Count'] / channel_stats['Created Count'] * 100).fillna(0)

# 4. DASHBOARD LOGIC
total_channels = len(channel_stats)
publishing_channels = channel_stats[channel_stats['Published Count'] > 0]
num_publishing = len(publishing_channels)
num_zero_publishing = total_channels - num_publishing

# Identify Best Channel
best_channel = channel_stats.sort_values(by='Publish_Rate_%', ascending=False).iloc[0]

# Platform-wide Creation Efficiency (Avg)
avg_creation_eff = channel_stats['Creation_Efficiency'].mean()

# 5. Output Summary
print("--- CHANNEL EXECUTIVE DASHBOARD ---")
print(f"Total Channels: {total_channels}")
print(f"Active (Publishing) Channels: {num_publishing}")
print(f"Inactive (Zero Publishing) Channels: {num_zero_publishing}")
print(f"Best Channel: {best_channel['Channel_Name']} ({best_channel['Publish_Rate_%']:.2f}% Rate)")
print(f"Avg Creation Efficiency: {avg_creation_eff:.2f}x")

# 6. Visualization: Publishing vs Non-Publishing
plt.figure(figsize=(8, 8))
labels = ['Publishing Channels', 'Zero Publishing']
sizes = [num_publishing, num_zero_publishing]
plt.pie(sizes, labels=labels, autopct='%1.1f%%', colors=['#2ecc71', '#e74c3c'], startangle=140)
plt.title('Channel Activity Distribution', fontweight='bold')
plt.savefig('channel_activity_pie.png')

"""Channel spotlight performance badges"""

import pandas as pd
import matplotlib.pyplot as plt

# 1. Load the relationship and performance files
df_user_channel = pd.read_csv('Fact_User_Channel.csv')
df_dim_channel = pd.read_csv('Dim_Channel.csv')

# 2. Aggregate metrics at the channel level
# We count unique User_IDs to get "No of User"
channel_agg = df_user_channel.groupby('Channel_ID').agg({
    'User_ID': 'nunique',
    'Uploaded Count': 'sum',
    'Created Count': 'sum',
    'Published Count': 'sum'
}).reset_index()

# 3. Merge with Dimension to get names
df_performance = pd.merge(channel_agg, df_dim_channel, on='Channel_ID')

# 4. KPI Calculations
# Creation Efficiency = (Clips Generated / Raw Videos Uploaded)
df_performance['Creation_Efficiency'] = (df_performance['Created Count'] / df_performance['Uploaded Count']).fillna(0)

# Publish Rate = (Final Published / Clips Generated) * 100
df_performance['Publish_Rate_%'] = (df_performance['Published Count'] / df_performance['Created Count'] * 100).fillna(0)

# 5. Clean up and rename for the report
report = df_performance[['Channel_Name', 'User_ID', 'Uploaded Count', 'Publish_Rate_%', 'Creation_Efficiency']]
report.columns = ['Channel Name', 'No. of Users', 'Total Uploaded', 'Publish Rate (%)', 'Creation Efficiency (x)']

# 6. Sorting by Success (Publish Rate)
report = report.sort_values(by='Publish Rate (%)', ascending=False)

# 7. Visualization: Users vs. Publish Rate
fig, ax1 = plt.subplots(figsize=(12, 6))

ax1.bar(report['Channel Name'], report['No. of Users'], color='#3498db', alpha=0.6, label='No. of Users')
ax1.set_ylabel('Number of Users', color='#3498db', fontweight='bold')
ax1.tick_params(axis='y', labelcolor='#3498db')

ax2 = ax1.twinx()
ax2.plot(report['Channel Name'], report['Publish Rate (%)'], color='#e74c3c', marker='o', linewidth=2, label='Publish Rate (%)')
ax2.set_ylabel('Publish Rate (%)', color='#e74c3c', fontweight='bold')
ax2.tick_params(axis='y', labelcolor='#e74c3c')

plt.title('Channel Performance: User Volume vs. Success Rate', fontsize=14, fontweight='bold')
ax1.set_xticklabels(report['Channel Name'], rotation=45)
plt.tight_layout()
plt.savefig('channel_performance_matrix.png')

# 8. Output
print(report.to_string(index=False))
report.to_csv('Channel_Performance_Summary.csv', index=False)

"""User leaderboard"""

import pandas as pd
import numpy as np

# 1. Load the real user data
df = pd.read_csv('Fact_User_Summary.csv')
dim_user = pd.read_csv('Dim_User.csv')

# Merge df with dim_user to get User_Name
df = pd.merge(df, dim_user, on='User_ID', how='left')

# 2. KPI Calculations
# Creation Efficiency (x) = Clips created per raw upload
df['Creation_Efficiency'] = (df['Created Count'] / df['Uploaded Count']).fillna(0)

# Publish Rate (%) = Final published vs clips created
df['Publish_Rate_%'] = (df['Published Count'] / df['Created Count'] * 100).fillna(0)

# 3. Tiering Logic
def assign_tier(row):
    if row['Published Count'] >= 10:
        return '🥇 Platinum'
    elif row['Published Count'] >= 5:
        return '🥈 Gold'
    elif row['Published Count'] > 0:
        return '🥉 Silver'
    elif row['Uploaded Count'] > 0:
        return '🧱 Bronze (Incomplete)'
    else:
        return '💤 Inactive'

df['User_Tier'] = df.apply(assign_tier, axis=1)

# 4. Final Leaderboard Construction
# Sort by Published Count first, then Efficiency
leaderboard = df.sort_values(by=['Published Count', 'Creation_Efficiency'], ascending=False).reset_index(drop=True)
leaderboard.insert(0, 'Rank', range(1, len(leaderboard) + 1))

# 5. Output
print("--- FULL 45-USER PERFORMANCE LEADERBOARD ---")
pd.set_option('display.max_rows', 50)
print(leaderboard[['Rank', 'User_Name', 'Uploaded Count', 'Created Count', 'Published Count',
                  'Publish_Rate_%', 'Creation_Efficiency', 'User_Tier']].to_string(index=False))

# 6. Save to CSV
leaderboard.to_csv('User_Performance_Tiers.csv', index=False)

"""Channel upload-created-publised comparison"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# 1. Load your channel performance data
df_fact = pd.read_csv('Fact_User_Channel.csv')
df_dim = pd.read_csv('Dim_Channel.csv')

# 2. Aggregate at the Channel Level
channel_comp = df_fact.groupby('Channel_ID').agg({
    'Uploaded Count': 'sum',
    'Created Count': 'sum',
    'Published Count': 'sum'
}).reset_index()

# 3. Merge with Dimension for names
df = pd.merge(channel_comp, df_dim, on='Channel_ID')

# 4. Sorting by Uploaded Volume for clarity
df = df.sort_values(by='Uploaded Count', ascending=False)

# 5. Visualization: Grouped Bar Chart
plt.figure(figsize=(15, 8))
x = np.arange(len(df['Channel_Name']))
width = 0.25

# Plotting the three stages of the funnel
plt.bar(x - width, df['Uploaded Count'], width, label='1. Uploaded (Raw)', color='#3498db')
plt.bar(x, df['Created Count'], width, label='2. Created (AI Clips)', color='#f1c40f')
plt.bar(x + width, df['Published Count'], width, label='3. Published (Live)', color='#2ecc71')

plt.xlabel('Channel Name', fontweight='bold')
plt.ylabel('Video Counts')
plt.title('Channel-wise Content Comparison: Upload -> Create -> Publish', fontsize=15, fontweight='bold')
plt.xticks(x, df['Channel_Name'], rotation=45)
plt.legend()
plt.grid(axis='y', linestyle='--', alpha=0.3)

plt.tight_layout()
plt.savefig('channel_funnel_comparison.png')

# 6. Output Comparison Matrix
print("--- CHANNEL COMPARISON MATRIX ---")
print(df[['Channel_Name', 'Uploaded Count', 'Created Count', 'Published Count']].to_string(index=False))

"""Top 12 user by publised count"""

import pandas as pd
import matplotlib.pyplot as plt

# 1. Load the user summary data
df = pd.read_csv('Fact_User_Summary.csv')
dim_user = pd.read_csv('Dim_User.csv')

# Merge df with dim_user to get User_Name
df = pd.merge(df, dim_user, on='User_ID', how='left')

# 2. Sort by Published Count and take the top 12
top_12_users = df.sort_values(by='Published Count', ascending=False).head(12)

# 3. Add Rank column
top_12_users.insert(0, 'Rank', range(1, 13))

# 4. Visualization: Bar Chart
plt.figure(figsize=(12, 7))
bars = plt.bar(top_12_users['User_Name'], top_12_users['Published Count'], color='#27ae60', edgecolor='black')

plt.title('Top 12 Users by Total Published Videos', fontsize=14, fontweight='bold')
plt.xlabel('User Name', fontsize=12)
plt.ylabel('Videos Published', fontsize=12)
plt.xticks(rotation=45, ha='right')

# Add exact count labels on top of the bars
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 0.2, int(yval),
             ha='center', va='bottom', fontweight='bold')

plt.tight_layout()
plt.savefig('top_12_users_published.png')

# 5. Output Data Table
print("--- TOP 12 USERS: PUBLISHED COUNT LEADERBOARD ---")
print(top_12_users[['Rank', 'User_Name', 'Published Count', 'Uploaded Count']].to_string(index=False))

"""user channel drilldown matrix"""

import pandas as pd

# 1. Load the relationship and performance files
# Fact_User_Channel contains the raw numbers per user per channel
# Dim_Channel and Dim_User provide the readable names
df_fact = pd.read_csv('Fact_User_Channel.csv')
df_dim_channel = pd.read_csv('Dim_Channel.csv')
df_dim_user = pd.read_csv('Dim_User.csv')

# 2. Merge all files into one master drilldown table
df = pd.merge(df_fact, df_dim_channel, on='Channel_ID')
df = pd.merge(df, df_dim_user, on='User_ID')

# 3. KPI Calculation: Rate % (Published / Uploaded)
# Note: Based on your example, Rate % = (Published Count / Uploaded Count) * 100
df['Rate %'] = (df['Published Count'] / df['Uploaded Count'] * 100).fillna(0).round(1).astype(str) + '%'

# 4. Select and Rename columns to match your request
drill_down_matrix = df[[
    'Channel_Name', 'User_Name', 'Uploaded Count',
    'Created Count', 'Published Count', 'Rate %'
]]

# 5. Sorting for better readability (Grouped by Channel)
drill_down_matrix = drill_down_matrix.sort_values(by=['Channel_Name', 'Published Count'], ascending=[True, False])

# 6. Save to CSV for external use
drill_down_matrix.to_csv('User_Channel_Drilldown.csv', index=False)

# 7. Print Result
print("--- USER CHANNEL DRILLDOWN MATRIX ---")
print(drill_down_matrix.to_string(index=False))