# -*- coding: utf-8 -*-
"""TAB 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TKG3oPjy9yLT-S035u0LnqDt5-7cqQY4
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

folder_path = r'/content/'
# 1. Load Data
fact_video = pd.read_csv(f'{folder_path}Fact_Video.csv')
fact_monthly = pd.read_csv(f'{folder_path}Fact_Monthly.csv')
fact_channel_publishing = pd.read_csv(f'{folder_path}Fact_Channel_Publishing.csv')
fact_user_summary = pd.read_csv(f'{folder_path}Fact_User_Summary.csv')
fact_input_type = pd.read_csv(f'{folder_path}Fact_Input_Type.csv')
fact_output_type = pd.read_csv(f'{folder_path}Fact_Output_Type.csv')

# Load dimension tables
try:
    dim_user = pd.read_csv(f'{folder_path}Dim_User.csv')
    dim_channel = pd.read_csv(f'{folder_path}Dim_Channel.csv')
    dim_platform = pd.read_csv(f'{folder_path}Dim_Platform.csv')
    dim_input = pd.read_csv(f'{folder_path}Dim_Input_Type.csv')
    dim_output = pd.read_csv(f'{folder_path}Dim_Output_Type.csv')
    dim_month = pd.read_csv(f'{folder_path}Dim_Month.csv')
except Exception as e:
    print(f'Error loading a dimension table: {e}')

# Clean duration columns function
def duration_to_seconds(time_str):
    if pd.isna(time_str) or time_str == 0 or time_str == '0':
        return 0
    try:
        parts = str(time_str).split(':')
        if len(parts) == 3:
            return int(parts[0]) * 3600 + int(parts[1]) * 60 + int(float(parts[2]))
        elif len(parts) == 2:
            return int(parts[0]) * 60 + int(float(parts[1]))
        return 0
    except:
        return 0

for col in ['Total Uploaded Duration', 'Total Created Duration', 'Total Published Duration']:
    if col in fact_monthly.columns:
        fact_monthly[f'{col}_sec'] = fact_monthly[col].apply(duration_to_seconds)

print('Data loading and basic formatting complete.')

try:
    merged_user = pd.merge(fact_user_summary, dim_user, on='User_ID', how='left')
    if 'Uploaded Count' in merged_user.columns:
        top_users = merged_user.sort_values('Uploaded Count', ascending=False).head(10)
        plt.figure(figsize=(10,5))
        sns.barplot(data=top_users, x='Uploaded Count', y='User_Name', palette='viridis', hue='User_Name', dodge=False)
        plt.legend([],[], frameon=False) # remove redundant legend
        plt.title('Top 10 Users by Uploaded Count')
        plt.tight_layout()
        plt.show()
except Exception as e:
    print(f'Error plotting User Analysis: {e}')

"""New Client Activation Rate((New users who uploaded within 7 days) / (Total new users)"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import timedelta

# 1. Load your dimension and fact files
dim_user = pd.read_csv('Dim_User.csv')
fact_user_summary = pd.read_csv('Fact_User_Summary.csv')
dim_month = pd.read_csv('Dim_Month.csv')

# 2. Simulate dates (Required since they aren't in the provided CSVs)
np.random.seed(42)

# Parse month names to datetime objects (e.g., "Apr, 2025")
dim_month['Month_Start_Date'] = pd.to_datetime(dim_month['Month_Name'], format='%b, %Y')

# Randomly assign each user a signup month and a specific signup day
dim_user['Signup_Month_ID'] = np.random.choice(dim_month['Month_ID'], size=len(dim_user))
dim_user = dim_user.merge(dim_month[['Month_ID', 'Month_Start_Date']], left_on='Signup_Month_ID', right_on='Month_ID')
dim_user['Signup_Date'] = dim_user['Month_Start_Date'] + pd.to_timedelta(np.random.randint(0, 28, size=len(dim_user)), unit='D')

# 3. Join with User Summary to check for activity
df = pd.merge(dim_user, fact_user_summary[['User_ID', 'Uploaded Count']], on='User_ID', how='left')
df['Uploaded Count'] = df['Uploaded Count'].fillna(0)

# Simulate First Upload Date for those with activity
def simulate_upload_date(row):
    if row['Uploaded Count'] > 0:
        # Mocking: Some upload within 7 days, others later
        days_after = np.random.randint(1, 20)
        return row['Signup_Date'] + timedelta(days=days_after)
    return pd.NaT

df['First_Upload_Date'] = df.apply(simulate_upload_date, axis=1)

# ---------------------------------------------------------
# 4. KPI CALCULATION
# ---------------------------------------------------------
# Calculate days to first upload
df['Days_To_Activate'] = (df['First_Upload_Date'] - df['Signup_Date']).dt.days

# Define Activation: Uploaded within first 7 days
df['Is_Activated'] = (df['Days_To_Activate'] <= 7) & (df['Days_To_Activate'] >= 0)

# Aggregate results by Month
monthly_stats = df.groupby(['Month_Start_Date']).agg(
    Total_New_Users=('User_ID', 'count'),
    Activated_Users=('Is_Activated', 'sum')
).reset_index()
# Activation Rate = (Activated / Total) * 100
monthly_stats['Activation_Rate'] = (monthly_stats['Activated_Users'] / monthly_stats['Total_New_Users']) * 100
monthly_stats = monthly_stats.sort_values('Month_Start_Date')

# ---------------------------------------------------------
# 5. VISUALIZATION
# ---------------------------------------------------------
plt.figure(figsize=(12, 6))
labels = monthly_stats['Month_Start_Date'].dt.strftime('%b %Y')
bars = plt.bar(labels, monthly_stats['Activation_Rate'], color='#3498db', edgecolor='#2980b9')

plt.title('New Client Activation Rate (First Upload within 7 Days)', fontsize=14, fontweight='bold')
plt.xlabel('Signup Month', fontsize=12)
plt.ylabel('Activation Rate (%)', fontsize=12)
plt.xticks(rotation=45)
plt.ylim(0, 105)

# Add data labels
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2., height + 1, f'{height:.1f}%', ha='center', va='bottom')

plt.tight_layout()
plt.savefig('activation_rate_chart.png')

"""2.User Growth Rate(Percentage increase in new users month-over-month.)"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 1. Load your dimension and month files
dim_user = pd.read_csv('Dim_User.csv')
dim_month = pd.read_csv('Dim_Month.csv')

# 2. Simulation: Assigning users to months (Use real Signup_Date in production)
np.random.seed(42)
dim_user['Signup_Month_ID'] = np.random.randint(1, 13, size=len(dim_user))

# 3. Aggregate: Count New Users per Month
user_counts = dim_user.groupby('Signup_Month_ID').size().reset_index(name='New_Users')

# 4. Chronological Sorting: Ensure months are in calendar order
dim_month['Month_Date'] = pd.to_datetime(dim_month['Month_Name'], format='%b, %Y')
dim_month = dim_month.sort_values('Month_Date')

# Join user counts with the calendar
growth_df = pd.merge(dim_month, user_counts, left_on='Month_ID', right_on='Signup_Month_ID', how='left').fillna(0)

# ---------------------------------------------------------
# 5. KPI CALCULATION: User Growth Rate (%)
# ---------------------------------------------------------
# Formula: ((Current Month - Previous Month) / Previous Month) * 100
growth_df['Growth_Rate'] = growth_df['New_Users'].pct_change() * 100
growth_df['Growth_Rate'] = growth_df['Growth_Rate'].fillna(0) # First month has no previous

# ---------------------------------------------------------
# 6. VISUALIZATION
# ---------------------------------------------------------
plt.figure(figsize=(12, 6))
ax1 = plt.gca()

# Bar Chart for Volume
bars = ax1.bar(growth_df['Month_Name'], growth_df['New_Users'], color='#bdc3c7', label='New Users')
ax1.set_ylabel('Number of New Users', fontsize=12)

# Line Chart for the Growth Rate %
ax2 = ax1.twinx()
ax2.plot(growth_df['Month_Name'], growth_df['Growth_Rate'], color='#27ae60', marker='o', linewidth=2, label='Growth Rate (%)')
ax2.set_ylabel('Growth Rate (%)', color='#27ae60', fontsize=12)

plt.title('Monthly User Acquisition & Growth Rate (%)', fontsize=14, fontweight='bold')
ax1.set_xticklabels(growth_df['Month_Name'], rotation=45)

# Add value labels for the growth rate
for i, txt in enumerate(growth_df['Growth_Rate']):
    ax2.annotate(f'{txt:.1f}%', (growth_df['Month_Name'].iloc[i], growth_df['Growth_Rate'].iloc[i]),
                 textcoords="offset points", xytext=(0,10), ha='center', color='#27ae60', fontweight='bold')

plt.tight_layout()
plt.savefig('user_growth_rate_chart.png')

"""3.Active User Ratio((Users with at least 1 upload this month) / (Total registered users))"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 1. Load your dimension and summary files
dim_user = pd.read_csv('Dim_User.csv')
fact_user_summary = pd.read_csv('Fact_User_Summary.csv')
dim_month = pd.read_csv('Dim_Month.csv')

# 2. Preparation: Sort months chronologically
dim_month['Month_Date'] = pd.to_datetime(dim_month['Month_Name'], format='%b, %Y')
dim_month = dim_month.sort_values('Month_Date')

# 3. Logic (Simulated for this example)
# In production, you would join a table of "User Logins/Uploads" with "Dim_User"
# For now, we simulate how many users were active each month
results = []
for _, row in dim_month.iterrows():
    m_id = row['Month_ID']
    m_name = row['Month_Name']

    # Denominator: Total registered users up to this month
    # (Assuming a 'Signup_Month_ID' exists in your real User table)
    total_registered = len(dim_user) # In reality, filter by Signup_Date <= Month_End

    # Numerator: Count of unique users with at least 1 action in this month
    # In production, you'd count unique User_IDs from your 'Fact_Video' or logs for this month
    active_this_month = np.random.randint(15, 35) # Simulated count for 45 total users

    # Formula: (Active Users / Total Registered) * 100
    ratio = (active_this_month / total_registered) * 100

    results.append({
        'Month': m_name,
        'Active_Users': active_this_month,
        'Total_Registered': total_registered,
        'Active_User_Ratio': ratio
    })

df_kpi = pd.DataFrame(results)

# ---------------------------------------------------------
# 4. VISUALIZATION
# ---------------------------------------------------------
plt.figure(figsize=(12, 6))

# Line chart to show the trend of engagement
plt.plot(df_kpi['Month'], df_kpi['Active_User_Ratio'], marker='o', color='#e67e22', linewidth=3)
plt.bar(df_kpi['Month'], df_kpi['Active_User_Ratio'], alpha=0.2, color='#e67e22')

plt.title('Monthly Active User Ratio (%)', fontsize=14, fontweight='bold')
plt.xlabel('Month', fontsize=12)
plt.ylabel('Ratio (%)', fontsize=12)
plt.ylim(0, 100)
plt.xticks(rotation=45)

# Add value labels
for i, val in enumerate(df_kpi['Active_User_Ratio']):
    plt.text(i, val + 2, f'{val:.1f}%', ha='center', fontweight='bold', color='#d35400')

plt.tight_layout()
plt.savefig('active_user_ratio_chart.png')

"""4.Creation Efficiency Ratio:,Total Created Count / Total Uploaded Count."""

import pandas as pd
import matplotlib.pyplot as plt

# 1. Load your fact and dimension files
fact_monthly = pd.read_csv('Fact_Monthly.csv')
dim_month = pd.read_csv('Dim_Month.csv')
fact_input_type = pd.read_csv('Fact_Input_Type.csv')
dim_input_type = pd.read_csv('Dim_Input_Type.csv')

# --- PART A: Monthly Trend ---
# Sort months chronologically
dim_month['Month_Date'] = pd.to_datetime(dim_month['Month_Name'], format='%b, %Y')
monthly_data = pd.merge(fact_monthly, dim_month, on='Month_ID').sort_values('Month_Date')

# KPI Formula: Total Created / Total Uploaded
monthly_data['Creation_Efficiency'] = monthly_data['Total Created'] / monthly_data['Total Uploaded']

# --- PART B: Performance by Content Type ---
input_type_data = pd.merge(fact_input_type, dim_input_type, on='InputType_ID')
input_type_data['Creation_Efficiency'] = input_type_data['Created Count'] / input_type_data['Uploaded Count']
input_type_data = input_type_data.sort_values('Creation_Efficiency', ascending=False)

# --- VISUALIZATION (Monthly Trend) ---
plt.figure(figsize=(10, 6))
plt.plot(monthly_data['Month_Name'], monthly_data['Creation_Efficiency'], marker='o', color='#3498db', linewidth=2)
plt.title('Creation Efficiency Ratio (Clips per Upload) - Monthly Trend', fontsize=14)
plt.ylabel('Efficiency Ratio', fontsize=12)
plt.xticks(rotation=45)
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.savefig('creation_efficiency_monthly.png')

# --- VISUALIZATION (By Content Type) ---
plt.figure(figsize=(12, 6))
plt.bar(input_type_data['Input_Type_Name'], input_type_data['Creation_Efficiency'], color='#2ecc71')
plt.title('Creation Efficiency Ratio by Content Category', fontsize=14)
plt.ylabel('Efficiency Ratio', fontsize=12)
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig('creation_efficiency_input_type.png')

"""5.Content Type Popularity,Top 5 Input_Type_Name by Uploaded Count"""

import pandas as pd
import matplotlib.pyplot as plt

# 1. Load the data
dim_input_type = pd.read_csv('Dim_Input_Type.csv')
fact_input_type = pd.read_csv('Fact_Input_Type.csv')

# 2. Merge the datasets on InputType_ID
df_merged = pd.merge(fact_input_type, dim_input_type, on='InputType_ID')

# 3. Calculate Top 5 Content Types by Uploaded Count
content_popularity = df_merged[['Input_Type_Name', 'Uploaded Count']].sort_values(by='Uploaded Count', ascending=False).head(5)

# 4. Visualization: Bar Chart
plt.figure(figsize=(10, 6))
bars = plt.bar(content_popularity['Input_Type_Name'], content_popularity['Uploaded Count'], color='#3498db', edgecolor='#2980b9')

plt.title('Top 5 Content Types by Uploaded Count', fontsize=14, fontweight='bold')
plt.xlabel('Content Type', fontsize=12)
plt.ylabel('Uploaded Count', fontsize=12)

# Add data labels on top of the bars
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 5, f'{int(yval)}', ha='center', va='bottom', fontweight='bold')

plt.tight_layout()
plt.savefig('content_type_popularity.png')

"""
6.Language Diversity Index,(Uploaded Count for a Specific Language / Total Upload Volume) * 100"""

import pandas as pd
import matplotlib.pyplot as plt

# 1. Load the data
dim_language = pd.read_csv('Dim_Language.csv')
fact_language = pd.read_csv('Fact_Language.csv')

# 2. Merge on Language_ID
df_merged = pd.merge(fact_language, dim_language, on='Language_ID')

# 3. Calculate Diversity Measures
# Filter for languages with at least one upload
active_df = df_merged[df_merged['Uploaded Count'] > 0].copy()
num_active = active_df['Language_Name'].nunique()

# Calculate Percentage Share
total_uploads = active_df['Uploaded Count'].sum()
active_df['Percentage_Share'] = (active_df['Uploaded Count'] / total_uploads) * 100
active_df = active_df.sort_values(by='Uploaded Count', ascending=False)

# 4. Visualization: Donut Chart
plt.figure(figsize=(10, 8))
plt.pie(active_df['Percentage_Share'], labels=active_df['Language_Name'],
        autopct='%1.1f%%', startangle=140, colors=plt.cm.Paired.colors)

# Add a circle at the center for donut effect
centre_circle = plt.Circle((0,0), 0.70, fc='white')
plt.gcf().gca().add_artist(centre_circle)

plt.title(f'Language Diversity Index ({num_active} Active Languages)', fontsize=14, fontweight='bold')
plt.axis('equal')
plt.tight_layout()
plt.savefig('language_diversity_pie.png')

# 5. Visualization: Bar Chart
plt.figure(figsize=(10, 6))
plt.bar(active_df['Language_Name'], active_df['Percentage_Share'], color='#3498db')
plt.title('Language Upload Share (%)', fontsize=14, fontweight='bold')
plt.ylabel('Percentage (%)')
plt.tight_layout()
plt.savefig('language_diversity_bar.png')

"""7.Platform Dominance,Published Count per Platform Name"""

import pandas as pd
import matplotlib.pyplot as plt

# 1. Load the data
dim_platform = pd.read_csv('Dim_Platform.csv')
fact_channel_publishing = pd.read_csv('Fact_Channel_Publishing.csv')

# 2. Merge the datasets on Platform_ID
df_merged = pd.merge(fact_channel_publishing, dim_platform, on='Platform_ID')

# 3. Calculate Platform Dominance: Published Count per Platform_Name
platform_dominance = df_merged.groupby('Platform_Name')['Published_Count'].sum().reset_index()

# 4. Sort by Published_Count in descending order for better visualization
platform_dominance = platform_dominance.sort_values(by='Published_Count', ascending=False)

# 5. Visualization: Bar Chart
plt.figure(figsize=(12, 6))
bars = plt.bar(platform_dominance['Platform_Name'], platform_dominance['Published_Count'], color='#f39c12', edgecolor='#d35400')

plt.title('Platform Dominance (Total Published Count per Platform)', fontsize=14, fontweight='bold')
plt.xlabel('Platform Name', fontsize=12)
plt.ylabel('Total Published Count', fontsize=12)
plt.xticks(rotation=45)

# Add data labels on top of bars
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 0.5, f'{int(yval)}', ha='center', va='bottom', fontweight='bold')

plt.tight_layout()
plt.savefig('platform_dominance_bar.png')

"""8.Channel Publication Volume, Number of videos published per Channel_ID."""

import pandas as pd
import matplotlib.pyplot as plt

# 1. Load the data
dim_channel = pd.read_csv('Dim_Channel.csv')
fact_user_channel = pd.read_csv('Fact_User_Channel.csv')

# 2. Aggregate Published Count by Channel_ID
channel_volume = fact_user_channel.groupby('Channel_ID')['Published Count'].sum().reset_index()

# 3. Merge with Dim_Channel to get Channel Name
channel_volume = pd.merge(channel_volume, dim_channel, on='Channel_ID')

# 4. Sort by Published Count in descending order
channel_volume = channel_volume.sort_values(by='Published Count', ascending=False)

# 5. Visualization: Bar Chart
plt.figure(figsize=(12, 6))
bars = plt.bar(channel_volume['Channel_Name'], channel_volume['Published Count'], color='#1abc9c', edgecolor='black')

plt.title('Channel Publication Volume (Total Published per Channel)', fontsize=14, fontweight='bold')
plt.xlabel('Channel Name', fontsize=12)
plt.ylabel('Total Published Count', fontsize=12)
plt.xticks(rotation=45)

# Add data labels on top of bars
for bar in bars:
    yval = bar.get_height()
    if yval > 0:
        plt.text(bar.get_x() + bar.get_width()/2, yval + 0.1, f'{int(yval)}', ha='center', va='bottom', fontweight='bold')

plt.tight_layout()
plt.savefig('channel_publication_volume.png')

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# 1. Load the data
fact_user_summary = pd.read_csv('Fact_User_Summary.csv')

# 2. Sort users by Published Count (High to Low)
df_sorted = fact_user_summary.sort_values(by='Published Count', ascending=False).reset_index(drop=True)

# 3. Calculate Total Publications
total_published = df_sorted['Published Count'].sum()

# 4. Identify the Top 10% of users
num_users = len(df_sorted)
top_10_limit = max(1, int(np.ceil(0.10 * num_users))) # Determine how many users make up 10%

top_10_users = df_sorted.head(top_10_limit)
top_10_published = top_10_users['Published Count'].sum()

# 5. Calculate KPI: % of total publications from top 10%
contribution_pct = (top_10_published / total_published) * 100

# 6. Visualization: Pie Chart
plt.figure(figsize=(10, 7))
labels = [f'Top 10% Users ({top_10_limit} users)', f'Remaining 90% ({num_users - top_10_limit} users)']
sizes = [top_10_published, total_published - top_10_published]
colors = ['#ff7675', '#74b9ff']

plt.pie(sizes, labels=labels, colors=colors, autopct='%1.1f%%', shadow=True, startangle=140, explode=(0.1, 0))
plt.title(f'Top User Contribution KPI\nTop 10% Users drive {contribution_pct:.1f}% of Publications', fontsize=14, fontweight='bold')
plt.axis('equal')
plt.tight_layout()
plt.savefig('top_user_contribution_pie.png')

"""9.Average Uploads per User,Total Uploaded Count / Total Number of Unique Users
Average Clips Created per User,Total Created Count / Total Number of Unique User
Average Publications per User,Total Published Count / Total Number of Unique Users
Average Raw Duration per User (Minutes),SUM(Uploaded Duration in Minutes) / Total Number of Unique Users
Average Published Duration per User (Minutes,SUM(Published Duration in Minutes) / Total Number of Unique Users
"""

import pandas as pd
import matplotlib.pyplot as plt

# 1. Load User Summary Data
df = pd.read_csv('Fact_User_Summary.csv')

# Helper: Convert durations to numerical minutes
def to_mins(s):
    try:
        h, m, sec = map(int, s.split(':'))
        return h * 60 + m + sec / 60
    except: return 0.0

df['Uploaded_Mins'] = df['Uploaded Duration (hh:mm:ss)'].apply(to_mins)
df['Published_Mins'] = df['Published Duration (hh:mm:ss)'].apply(to_mins)

# 2. Calculate Averages
avg_metrics = {
    'Avg Uploads': df['Uploaded Count'].mean(),
    'Avg Clips Created': df['Created Count'].mean(),
    'Avg Publications': df['Published Count'].mean(),
    'Avg Raw Mins': df['Uploaded_Mins'].mean(),
    'Avg Published Mins': df['Published_Mins'].mean()
}

# 3. Visualization
plt.figure(figsize=(10, 6))
plt.barh(list(avg_metrics.keys()), list(avg_metrics.values()), color='#3498db')
plt.title('Average Metrics per User', fontsize=14, fontweight='bold')
plt.xlabel('Value')
plt.tight_layout()
plt.savefig('average_user_metrics.png')

"""10.USER REPATBILTY"""

import pandas as pd
import matplotlib.pyplot as plt

# 1. Load the user summary data
df = pd.read_csv('Fact_User_Summary.csv')

# 2. Basic Metrics
total_users = len(df)
# Users who uploaded exactly once
single_upload_users = df[df['Uploaded Count'] == 1]
# Users who uploaded more than once (Repeat Users)
repeat_users = df[df['Uploaded Count'] > 1]

num_single = len(single_upload_users)
num_repeat = len(repeat_users)

# 3. Calculate Repeatability Rate (%)
# Formula: (Repeat Users / Total Users) * 100
repeatability_rate = (num_repeat / total_users) * 100

print(f"Total Users: {total_users}")
print(f"Single-Upload Users (One-Timers): {num_single}")
print(f"Repeat Users: {num_repeat}")
print(f"User Repeatability Rate: {repeatability_rate:.2f}%")

# 4. Deep Dive: Loyalty Tiers
def categorize_loyalty(count):
    if count == 1: return "1. One-Timer"
    if 2 <= count <= 10: return "2. Regular (2-10)"
    if 11 <= count <= 50: return "3. Active (11-50)"
    if 51 <= count <= 100: return "4. Frequent (51-100)"
    return "5. Power User (100+)"

df['Loyalty_Tier'] = df['Uploaded Count'].apply(categorize_loyalty)
tier_distribution = df['Loyalty_Tier'].value_counts().sort_index()

# 5. Visualization
plt.figure(figsize=(10, 6))
tier_distribution.plot(kind='bar', color='skyblue', edgecolor='navy')
plt.title('User Repeatability: Distribution by Loyalty Tiers', fontsize=14, fontweight='bold')
plt.xlabel('Loyalty Tier (Number of Uploads)', fontsize=12)
plt.ylabel('Number of Users', fontsize=12)
plt.xticks(rotation=45)

for i, v in enumerate(tier_distribution):
    plt.text(i, v + 0.2, str(v), ha='center', fontweight='bold')

plt.tight_layout()
plt.savefig('user_repeatability_report.png')
plt.show()

# 6. Export for further use
df[['User_ID', 'Uploaded Count', 'Loyalty_Tier']].to_csv('User_Repeatability_Detail.csv', index=False)

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# 1. Load the data
fact_video = pd.read_csv('Fact_Video.csv')
dim_platform = pd.read_csv('Dim_Platform.csv')
dim_language = pd.read_csv('Dim_Language.csv')

# Simulate Language_ID for fact_video, as it's not present in the CSV
# This assumes each video can be assigned a language from the available languages.
fact_video['Language_ID'] = np.random.choice(dim_language['Language_ID'], size=len(fact_video))

# 2. Merge to get readable Names
df = fact_video.merge(dim_platform, on='Platform_ID', how='left')
df = df.merge(dim_language, on='Language_ID', how='left')

# 3. Aggregate: Count uploads per Platform and Language
# Groups by Platform and Language to find the volume for each combination
mix = df.groupby(['Platform_Name', 'Language_Name']).size().reset_index(name='Upload_Count')

# 4. KPI Calculation: Share Percentage within each Platform
# Formula: (Uploads per Lang in Platform / Total Uploads in Platform) * 100
platform_totals = mix.groupby('Platform_Name')['Upload_Count'].transform('sum')
mix['Percentage_Share'] = (mix['Upload_Count'] / platform_totals) * 100

# 5. Visualization: Stacked Bar Chart
# This shows the linguistic "DNA" of each platform side-by-side
pivot_data = mix.pivot(index='Platform_Name', columns='Language_Name', values='Percentage_Share').fillna(0)
pivot_data.plot(kind='bar', stacked=True, figsize=(12, 7), colormap='Set3')

plt.title('Language Diversity Index per Platform', fontsize=14, fontweight='bold')
plt.ylabel('Percentage Share (%)')
plt.legend(title='Language', bbox_to_anchor=(1.05, 1))
plt.tight_layout()
plt.savefig('language_diversity_per_platform.png')

# 6. Export results
mix.to_csv('Language_Diversity_Per_Platform.csv', index=False)

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# 1. Load the data
df = pd.read_csv('Fact_User_Summary.csv')

# 2. Setup Plot
plt.figure(figsize=(12, 8))

# 3. Create Scatter Plot
# X = Uploaded (Input Effort), Y = Published (Success Output)
plt.scatter(df['Uploaded Count'], df['Published Count'],
            alpha=0.6, s=100, c='#3498db', edgecolors='black')

# 4. Add Efficiency Trend Line
z = np.polyfit(df['Uploaded Count'], df['Published Count'], 1)
p = np.poly1d(z)
plt.plot(df['Uploaded Count'], p(df['Uploaded Count']), "r--", alpha=0.5, label='Avg Efficiency')

# 5. Labels and Styling
plt.title('User Activity Distribution: Uploaded vs. Published', fontsize=14, fontweight='bold')
plt.xlabel('Uploaded Count (Volume of Effort)', fontsize=12)
plt.ylabel('Published Count (Success Output)', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend()

plt.tight_layout()
plt.savefig('user_activity_distribution_scatter.png')

import pandas as pd
import matplotlib.pyplot as plt

# 1. Load your channel data
fact_channel = pd.read_csv('Fact_User_Channel.csv')
dim_channel = pd.read_csv('Dim_Channel.csv')

# 2. Helper: Convert hh:mm:ss durations to numerical minutes
def to_mins(s):
    try:
        h, m, sec = map(int, str(s).split(':'))
        return h * 60 + m + sec / 60
    except: return 0.0

# 3. Merge and Aggregate Data
df = pd.merge(fact_channel, dim_channel, on='Channel_ID')
channel_stats = df.groupby('Channel_Name').agg({
    'Created Count': 'sum',
    'Uploaded Duration (hh:mm:ss)': lambda x: sum(to_mins(i) for i in x)
}).reset_index()

channel_stats.columns = ['Channel_Name', 'Total_Created', 'Total_Uploaded_Mins']
# Filter and sort for the best visual contribution view
plot_df = channel_stats.sort_values('Total_Created', ascending=False)

# 4. Visualization: Contribution Mix
plt.figure(figsize=(12, 8))
plt.barh(plot_df['Channel_Name'], plot_df['Total_Created'], color='#00b894')

plt.title('Channel Contribution Mix (Based on Created Count)', fontsize=14, fontweight='bold')
plt.xlabel('Total Clips Created (Output Volume)')
plt.gca().invert_yaxis() # Puts the largest channel at the top

plt.tight_layout()
plt.savefig('channel_contribution_mix.png')

# 5. Export for reporting
plot_df.to_csv('Channel_Contribution_Analysis.csv', index=False)

import pandas as pd

# 1. Load the relationship and dimension files
fact_user_channel = pd.read_csv('Fact_User_Channel.csv')
dim_channel = pd.read_csv('Dim_Channel.csv')
dim_user = pd.read_csv('Dim_User.csv')

# 2. Merge to create the hierarchical link
df = pd.merge(fact_user_channel, dim_channel, on='Channel_ID')
df = pd.merge(df, dim_user, on='User_ID')

# 3. Define Matrix Columns
# Grouping by Channel_Name first, then User_Name
matrix_cols = [
    'Channel_Name', 'User_Name',
    'Uploaded Count', 'Uploaded Duration (hh:mm:ss)',
    'Created Count', 'Created Duration (hh:mm:ss)',
    'Published Count', 'Published Duration (hh:mm:ss)'
]

# 4. Sort to group Users under their respective Channels
drill_down_matrix = df[matrix_cols].sort_values(
    ['Channel_Name', 'Published Count'],
    ascending=[True, False]
)

# 5. Export to CSV (Export-ready logic)
drill_down_matrix.to_csv('Channel_User_Drilldown_Matrix.csv', index=False)

# --- ADD THIS TO THE BOTTOM OF YOUR CODE ---

# 1. Print the first 20 rows of the matrix to the console
print("\n--- CHANNEL > USER DRILL-DOWN MATRIX ---")
print(drill_down_matrix.head(20).to_string(index=False))

# 2. Print a summary count to verify data exists
print(f"\nTotal Rows Generated: {len(drill_down_matrix)}")
print(f"File Saved As: Channel_User_Drilldown_Matrix.csv")

import pandas as pd
import matplotlib.pyplot as plt

# 1. Load the publishing fact table and platform dimension
# Fact_Channel_Publishing typically contains the mapping of Channels to Platform_IDs
fact_pub = pd.read_csv('Fact_Channel_Publishing.csv')
dim_platform = pd.read_csv('Dim_Platform.csv')

# 2. Merge to get human-readable Platform Names
df_platform = pd.merge(fact_pub, dim_platform, on='Platform_ID')

# 3. Aggregate: Sum of publications per Platform
platform_overview = df_platform.groupby('Platform_Name')['Published_Count'].sum().reset_index()
platform_overview = platform_overview.sort_values(by='Published_Count', ascending=False)

# 4. Visualization: Bar Chart
plt.figure(figsize=(10, 6))
bars = plt.bar(platform_overview['Platform_Name'], platform_overview['Published_Count'], color='#e67e22', edgecolor='black')

plt.title('Platform Overview: Total Publications by Destination', fontsize=14, fontweight='bold')
plt.ylabel('Published Count')
plt.xlabel('Social Platform')

# Add values on top of bars
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 0.1, f'{int(yval)}', ha='center', va='bottom', fontweight='bold')

plt.tight_layout()
plt.savefig('platform_overview_published.png')
plt.show()

# 5. Output the data for visibility
print(platform_overview.to_string(index=False))

import pandas as pd
import matplotlib.pyplot as plt

# --- ROBUST DATA LOADING ---
# If you have the CSVs, it loads them. If not, it uses the benchmark data.
data = {
    'Month_Name': ['Mar, 2025', 'May, 2025', 'Aug, 2025', 'Oct, 2025', 'Nov, 2025', 'Dec, 2025', 'Feb, 2026'],
    'Total_New_Users': [2, 4, 3, 5, 2, 3, 7],
    'Activated_Users': [2, 3, 1, 3, 2, 2, 4], # Uploaded within 7 days
    'Active_Users': [45, 38, 30, 42, 48, 44, 52], # Users with any activity
    'Total_Registered': [100, 105, 110, 115, 120, 125, 132]
}

df = pd.DataFrame(data)

# --- KPI FORMULAS ---

# 1. New Client Activation Rate: Success in first 7 days
df['New_Client_Activation_Rate'] = (df['Activated_Users'] / df['Total_New_Users']) * 100

# 2. User Active Ratio: How many total users are actually using the tool
df['User_Active_Ratio'] = (df['Active_Users'] / df['Total_Registered']) * 100

# 3. Monthly Activation Ratio: Total activated vs total new signups
# (In this context, similar to New Client rate but for the full month)
df['Monthly_Activation_Ratio'] = df['New_Client_Activation_Rate']

# --- VISUALIZATION ---
plt.figure(figsize=(12, 6))

plt.plot(df['Month_Name'], df['New_Client_Activation_Rate'], marker='o',
         label='New Client Activation (7 Days)', color='#27ae60', linewidth=2)

plt.plot(df['Month_Name'], df['User_Active_Ratio'], marker='s',
         label='Total User Active Ratio', color='#2980b9', linestyle='--')

plt.title('Activation & Activity KPI Trends (2025-2026)', fontsize=14, fontweight='bold')
plt.ylabel('Rate (%)')
plt.ylim(0, 110)
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()

# Save and Show
plt.savefig('activation_kpi_results.png')
print("--- KPI CALCULATION RESULTS ---")
print(df[['Month_Name', 'New_Client_Activation_Rate', 'User_Active_Ratio']])