# -*- coding: utf-8 -*-
"""Tab4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sME6pOP5zEwu1_2VD4gToQeorbQRkj5B

# Frammer Data: Tab 4 KPIs
This notebook covers all the KPIs required to effectively represent Tab 4
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

import plotly.graph_objects as go
import plotly.io as pio

# --- FRAMMER AI BRAND THEME ---
frammer_bg = '#0F0F0F'          # Deep black background from the logo
frammer_red = '#F24E5B'         # Vibrant coral/red from the text
frammer_light_red = '#FF8A94'   # Lighter accent
frammer_dark_red = '#9E2A33'    # Darker accent for contrast
frammer_text = '#F5F5F5'        # Off-white for readable text
frammer_grid = '#2A2A2A'        # Subtle dark grey for gridlines

# Matplotlib & Seaborn Global Setup
frammer_palette = [frammer_red, frammer_light_red, '#E0E0E0', frammer_dark_red, '#757575', '#A3A3A3']

plt.rcParams.update({
    'figure.facecolor': frammer_bg,
    'axes.facecolor': frammer_bg,
    'axes.edgecolor': frammer_grid,
    'axes.labelcolor': frammer_text,
    'text.color': frammer_text,
    'xtick.color': frammer_text,
    'ytick.color': frammer_text,
    'grid.color': frammer_grid,
    'legend.facecolor': frammer_bg,
    'legend.edgecolor': frammer_grid,
    'legend.labelcolor': frammer_text
})
sns.set_palette(frammer_palette)

# Plotly Global Setup
pio.templates["frammer_dark"] = go.layout.Template(
    layout=go.Layout(
        paper_bgcolor=frammer_bg,
        plot_bgcolor=frammer_bg,
        font=dict(color=frammer_text),
        colorway=frammer_palette,
        xaxis=dict(gridcolor=frammer_grid, zerolinecolor=frammer_grid),
        yaxis=dict(gridcolor=frammer_grid, zerolinecolor=frammer_grid)
    )
)
pio.templates.default = "frammer_dark"

# Update folder_path to the Google Drive mount point
folder_path = r'/var'

# 1. Load Data
# Using the exact filenames provided by the user
fact_video = pd.read_csv(f'{folder_path}/Fact_Video (1).csv')
fact_monthly = pd.read_excel(f'{folder_path}/Fact_Monthly.xlsx') # Use read_excel for .xlsx files
fact_channel_publishing = pd.read_csv(f'{folder_path}/Fact_Channel_Publishing (1).csv')
fact_user_summary = pd.read_csv(f'{folder_path}/Fact_User_Summary (1).csv')
fact_input_type = pd.read_csv(f'{folder_path}/Fact_Input_Type (1).csv')
fact_output_type = pd.read_csv(f'{folder_path}/Fact_Output_Type (1).csv')

# Load dimension tables
try:
    dim_user = pd.read_csv(f'{folder_path}/Dim_User (1).csv')
    dim_channel = pd.read_csv(f'{folder_path}/Dim_Channel (1).csv')
    dim_platform = pd.read_csv(f'{folder_path}/Dim_Platform (1).csv')
    dim_input = pd.read_csv(f'{folder_path}/Dim_Input_Type (1).csv')
    dim_output = pd.read_csv(f'{folder_path}/Dim_Output_Type (1).csv')
    dim_month = pd.read_csv(f'{folder_path}/Dim_Month (1).csv')
except Exception as e:
    print(f'Error loading a dimension table: {e}')

# Create a dictionary to keep things organized
dataframes = {
    "Fact Video": fact_video,
    "Fact Monthly": fact_monthly,
    "Fact Channel Publishing": fact_channel_publishing,
    "Fact User Summary": fact_user_summary,
    "Fact Input Type": fact_input_type,
    "Fact Output Type": fact_output_type,
    "Dim User": dim_user,
    "Dim Channel": dim_channel,
    "Dim Platform": dim_platform,
    "Dim Input": dim_input,
    "Dim Output": dim_output,
    "Dim Month": dim_month
}

# Print headers and columns for each
for name, df in dataframes.items():
    print(f"--- {name} ---")
    print(df.columns.tolist())
    print("\n")

"""## Basic Processing
Formatting and cleaning duration columns from `hh:mm:ss` to seconds.
"""

# Clean duration columns function
def duration_to_seconds(time_str):
    if pd.isna(time_str) or time_str == 0 or time_str == '0':
        return 0
    try:
        parts = str(time_str).split(':')
        if len(parts) == 3:
            return int(parts[0]) * 3600 + int(parts[1]) * 60 + int(float(parts[2]))
        elif len(parts) == 2:
            return int(parts[0]) * 60 + int(float(parts[1]))
        return 0
    except:
        return 0

for col in ['Total Uploaded Duration', 'Total Created Duration', 'Total Published Duration']:
    if col in fact_monthly.columns:
        fact_monthly[f'{col}_sec'] = fact_monthly[col].apply(duration_to_seconds)

print('Data loading and basic formatting complete.')

"""## 1. Executive Summary
Top KPIs, trends, comparisons, alerts.
"""

print('--- Executive Summary: Top KPIs ---')
total_uploaded = fact_monthly['Total Uploaded'].sum()
total_created = fact_monthly['Total Created'].sum()
total_published = fact_monthly['Total Published'].sum()

print(f'Total Uploaded: {total_uploaded:,}')
print(f'Total Processed/Created: {total_created:,}')
print(f'Total Published: {total_published:,}')
conversion_rate = (total_published / total_uploaded * 100) if total_uploaded > 0 else 0
print(f'Overall Publish Conversion Rate: {conversion_rate:.2f}%\n')

# Trend Chart
# Trend Chart
try:
    merged_monthly = pd.merge(fact_monthly, dim_month, on='Month_ID', how='left')
    x_axis = merged_monthly['Month_Name'] if 'Month_Name' in merged_monthly.columns else merged_monthly['Month_ID']

    plt.figure(figsize=(10,5))
    plt.plot(x_axis, merged_monthly['Total Uploaded'], label='Uploaded', marker='o', color=frammer_light_red)
    plt.plot(x_axis, merged_monthly['Total Published'], label='Published', marker='s', color=frammer_red, linewidth=2)
    plt.title('Monthly Trend: Uploaded vs Published', color=frammer_text)
    plt.xlabel('Month')
    plt.ylabel('Count')
    plt.legend()
    plt.grid(True, color=frammer_grid)
    plt.tight_layout()
    plt.show()
except Exception as e:
    print(f'Unable to generate trend chart: {e}')

"""## 2. Usage & Trends
Time-based charts (count + duration), period comparison.
"""

try:
    fig, ax1 = plt.subplots(figsize=(10, 5))
    ax2 = ax1.twinx()

    x_axis_pos = range(len(merged_monthly))
    x_labels = merged_monthly['Month_Name'] if 'Month_Name' in merged_monthly.columns else merged_monthly['Month_ID']

    # Using frammer_dark_red for bars, bright frammer_red for the line overlay
    ax1.bar(x_axis_pos, merged_monthly['Total Uploaded'], color=frammer_dark_red, alpha=0.8, label='Count (left)')
    ax2.plot(x_axis_pos, merged_monthly['Total Uploaded Duration_sec'] / 3600, color=frammer_red, marker='o', linewidth=2.5, label='Duration (hrs, right)')

    ax1.set_xlabel('Month')
    ax1.set_xticks(x_axis_pos)
    ax1.set_xticklabels(x_labels, rotation=45)
    ax1.set_ylabel('Uploaded Count', color=frammer_light_red)
    ax2.set_ylabel('Uploaded Duration (Hours)', color=frammer_red)

    plt.title('Usage Trend: Count vs Duration', color=frammer_text)
    plt.tight_layout()
    plt.show()
except Exception as e:
    print(f'Unable to generate Usage & Trends chart: {e}')

"""## 3. Client / Channel / User Analysis
Breakdown and drill-down views.
"""

try:
    merged_user = pd.merge(fact_user_summary, dim_user, on='User_ID', how='left')
    if 'Uploaded Count' in merged_user.columns:
        top_users = merged_user.sort_values('Uploaded Count', ascending=False).head(10)
        plt.figure(figsize=(10,5))
        sns.barplot(data=top_users, x='Uploaded Count', y='User_Name', palette='viridis', hue='User_Name', dodge=False)
        plt.legend([],[], frameon=False) # remove redundant legend
        plt.title('Top 10 Users by Uploaded Count')
        plt.tight_layout()
        plt.show()
except Exception as e:
    print(f'Error plotting User Analysis: {e}')

"""## 4. Type Mix & Publishing Funnel
Processed vs Published, conversion, output type + input type mix.
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Assuming these variables are defined in your environment:
# frammer_palette = ['#F24E5B', '#FF8E94', '#2D2D2D', '#5E5E5E']
# frammer_bg = '#0F0F0F'
# frammer_text = '#FFFFFF'

try:
    merged_input = pd.merge(fact_input_type, dim_input, on='InputType_ID', how='left')

    # Sort data for a cleaner bar chart
    merged_input = merged_input.sort_values(by='Uploaded Count', ascending=True)

    # Set up the figure with the dark theme background
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 7), facecolor=frammer_bg)
    ax1.set_facecolor(frammer_bg)
    ax2.set_facecolor(frammer_bg)

    # --- CHART 1: TYPE MIX (Horizontal Bar Chart) ---
    # Horizontal bars are much easier to read than pie slices
    bars = ax1.barh(merged_input['Input_Type_Name'], merged_input['Uploaded Count'],
                    color='#F24E5B', edgecolor=frammer_bg, height=0.6)

    ax1.set_title('Content Type Distribution', color=frammer_text, fontsize=14, pad=20, weight='bold')
    ax1.tick_params(colors=frammer_text, labelsize=10)
    ax1.spines['top'].set_visible(False)
    ax1.spines['right'].set_visible(False)
    ax1.spines['bottom'].set_color('#333333')
    ax1.spines['left'].set_color('#333333')

    # Add count labels to the end of bars
    for bar in bars:
        width = bar.get_width()
        ax1.text(width + (width * 0.02), bar.get_y() + bar.get_height()/2,
                 f'{int(width)}', color=frammer_text, va='center', fontweight='bold')

    # --- CHART 2: PUBLISHING FUNNEL (Improved Funnel) ---
    funnel_data = [total_uploaded, total_created, total_published]
    funnel_labels = ['📥 Uploaded', '⚙️ Processed', '🚀 Published']

    # Calculate conversion rates for the funnel
    conv_rates = [100.0]
    for i in range(1, len(funnel_data)):
        rate = (funnel_data[i] / funnel_data[i-1]) * 100 if funnel_data[i-1] > 0 else 0
        conv_rates.append(rate)

    # Use a color gradient for the funnel steps
    funnel_colors = sns.color_palette("flare", n_colors=3) # Or use [frammer_accent, mid_tone, dark_tone]

    sns.barplot(x=funnel_data, y=funnel_labels, palette=funnel_colors, ax=ax2)

    ax2.set_title('Publishing Efficiency Funnel', color=frammer_text, fontsize=14, pad=20, weight='bold')
    ax2.tick_params(colors=frammer_text, labelsize=10)
    ax2.spines['top'].set_visible(False)
    ax2.spines['right'].set_visible(False)

    # Add data labels and conversion %
    for i, (v, rate) in enumerate(zip(funnel_data, conv_rates)):
        label_text = f"{v} ({rate:.1f}% yield)" if i > 0 else f"{v}"
        ax2.text(v + (max(funnel_data)*0.02), i, label_text, color=frammer_text, va='center', fontweight='bold')

    plt.tight_layout()
    plt.show()

except Exception as e:
    print(f'Error plotting Type Mix or Funnel: {e}')

"""## 5. Video-Level Detail / Explorer
Searchable, filterable detail table with export-ready logic.
"""

# Enrich Fact_Video for detail view
try:
    enriched_video = pd.merge(fact_video, dim_user, on='User_ID', how='left')
    enriched_video = pd.merge(enriched_video, dim_platform, on='Platform_ID', how='left')

    # Example filter: Published == 'Yes' (can be adjusted by user)
    filtered_detail = enriched_video[enriched_video['Published'] == 'Yes'].copy()

    print(f"Total Published Videos matching criteria: {len(filtered_detail)}\n")

    # Define columns to show in the explorer UI
    cols_to_show = ['Headline', 'Type', 'User_Name', 'Platform_Name', 'Published URL']
    display_df = filtered_detail[cols_to_show].head(10)

    from IPython.display import display, HTML
    display(HTML("<h4>Filtered Detail Explorer (Top 10 Rows)</h4>"))
    display(display_df)

    # Export-ready logic (Uncomment to export)
    # export_path = os.path.join(folder_path, 'video_export.csv')
    # filtered_detail[cols_to_show].to_csv(export_path, index=False)
    # print(f'\nExported data to {export_path}')
except Exception as e:
    print(f'Error generating Detail Explorer: {e}')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import entropy

# Convert Duration strings to Seconds
def duration_to_seconds(time_str):
    if pd.isna(time_str) or str(time_str).strip() in ['0', '0:00:00', '']:
        return 0
    try:
        parts = str(time_str).split(':')
        if len(parts) == 3:
            return int(parts[0]) * 3600 + int(parts[1]) * 60 + int(float(parts[2]))
        elif len(parts) == 2:
            return int(parts[0]) * 60 + int(float(parts[1]))
        return 0
    except: return 0

# Loading & Pre-processing
dim_channel = pd.read_csv('/var/Dim_Channel (1).csv')
dim_platform = pd.read_csv('/var/Dim_Platform (1).csv')
fact_input_type = pd.read_csv('/var/Fact_Input_Type (1).csv')
fact_channel_pub = pd.read_csv('/var/Fact_Channel_Publishing (1).csv')

for col in ['Uploaded Duration (hh:mm:ss)', 'Created Duration (hh:mm:ss)']:
    fact_input_type[f'{col}_sec'] = fact_input_type[col].apply(duration_to_seconds)

# --- Innovative KPI: VWES (Value-Weighted Efficiency Score) ---
# Weighting based on Output Type (Chapters=1.5, Key Moments=1.2, etc.)
# Logic: Sum(Published * W_type * W_billable) / Sum(Created_Duration)
# Note: Implemented as a row-level calculation on Fact_Video (mocked below for demonstration)
weights_type = {1: 1.0, 2: 1.2, 3: 1.5, 4: 1.2, 5: 0.8}

"""# **KPI 1 - Content Efficiency Funnel**
CEI represents the percentage of created content assets that are successfully published to a target platform. It is a measure of yield.

In a high-performing content engine, a low CEI indicates a "leaky" process where resources (time, money, and creative energy) are spent on assets that never see the light of day due to rejection, shifting priorities, or technical failures.

CEI = (Total Published Count / Total Created Count) * 100
"""

import plotly.graph_objects as go

# KPI 1: Funnel Efficiency
# CEI: Content Efficiency Index
# Wastage Rate: Percent of processed content not published

total_uploaded = fact_input_type['Uploaded Count'].sum()
total_created = fact_input_type['Created Count'].sum()
total_published = fact_input_type['Published Count'].sum()

cei = (total_published / total_created * 100)
wastage = ((total_created - total_published) / total_created * 100)
dur_amp = fact_input_type['Created Duration (hh:mm:ss)_sec'].sum() / fact_input_type['Uploaded Duration (hh:mm:ss)_sec'].sum()

# Using the calculated variables
stages = ["Total Created", "Total Published"]
values = [total_created, total_published]

fig_funnel = go.Figure(go.Funnel(
    y=stages,
    x=values,
    textinfo="value+percent initial",
    marker={"color": ["#636EFA", "#00CC96"]},
    connector={"line": {"color": "royalblue", "dash": "dot", "width": 3}}
))

fig_funnel.update_layout(
    title=f"Content Efficiency Funnel (CEI: {cei:.1f}%)",
    template="plotly_white"
)

# KPI 1: Funnel Efficiency
fig_funnel = go.Figure(go.Funnel(
    y=stages,
    x=values,
    textinfo="value+percent initial",
    marker={"color": [frammer_dark_red, frammer_red]},
    connector={"line": {"color": frammer_grid, "dash": "dot", "width": 3}}
))
fig_funnel.update_layout(title=f"Content Efficiency Funnel (CEI: {cei:.1f}%)")
fig_funnel.show()

"""# **KPI 2 - Duration Amplification Ratio**
Duration Amplification is a Multiplier metric. It quantifies the efficiency of your editing and repurposing workflow. This KPI tracks content density.

Dur_amp = Sum (content duration) / Sum (uploaded duration)

Explanation of three different zones -

The Red Zone ($0.0$ to $1.0$):
You are outputting less time than you imported. This is typical for high-end documentary or commercial work where 10 hours of raw footage is distilled into a 30-second masterpiece. In high-volume social media, however, it might suggest you aren't squeezing enough value out of your raw files.

The Gray Zone ($1.0$ to $2.5$):
You are generating a slight surplus. For every hour of raw video, you’re producing about 1.5 to 2 hours of content. This usually means you're creating the main video plus a few "Key Moments" clips.

The Green Zone ($2.5$ to $5.0$):
High-efficiency repurposing. One raw interview is being chopped into dozens of Chapters, Shorts and Highlights.
"""

# KPI 2: Duration Amplification Ratio

# Convert Duration strings to Seconds (Duplicated here for self-containment)
def duration_to_seconds(time_str):
    if pd.isna(time_str) or str(time_str).strip() in ['0', '0:00:00', '']:
        return 0
    try:
        parts = str(time_str).split(':')
        if len(parts) == 3:
            return int(parts[0]) * 3600 + int(parts[1]) * 60 + int(float(parts[2]))
        elif len(parts) == 2:
            return int(parts[0]) * 60 + int(float(parts[1]))
        return 0
    except: return 0

# Ensure fact_input_type has the _sec columns (Duplicated here for self-containment)
# This assumes fact_input_type has been loaded into the environment (e.g., by initial data loading cells).
# If fact_input_type is not yet loaded, you might need to add: fact_input_type = pd.read_csv(f'{folder_path}/Fact_Input_Type (1).csv')

# Check if '_sec' columns already exist to avoid re-running if not needed
if 'Uploaded Duration (hh:mm:ss)_sec' not in fact_input_type.columns:
    fact_input_type['Uploaded Duration (hh:mm:ss)_sec'] = fact_input_type['Uploaded Duration (hh:mm:ss)'].apply(duration_to_seconds)
if 'Created Duration (hh:mm:ss)_sec' not in fact_input_type.columns:
    fact_input_type['Created Duration (hh:mm:ss)_sec'] = fact_input_type['Created Duration (hh:mm:ss)'].apply(duration_to_seconds)

# Calculate dur_amp (Duplicated here for self-containment)
# Assuming total_uploaded and total_created are defined from previous cells, otherwise they would need to be re-calculated.
dur_amp = fact_input_type['Created Duration (hh:mm:ss)_sec'].sum() / fact_input_type['Uploaded Duration (hh:mm:ss)_sec'].sum()


fig_gauge = go.Figure(go.Indicator(
    mode="gauge+number",
    value=dur_amp,
    title={'text': "Duration Amplification Ratio", 'font': {'color': frammer_text}},
    domain={'x': [0, 1], 'y': [0, 1]},
    gauge={
        'axis': {'range': [0, 5], 'tickcolor': frammer_text},
        'bar': {'color': frammer_red},
        'bgcolor': frammer_bg,
        'steps': [
            {'range': [0, 1], 'color': "#333333"},    # Dark Grey
            {'range': [1, 2.5], 'color': "#555555"},  # Mid Grey
            {'range': [2.5, 5], 'color': frammer_dark_red} # Frammer Red Accent
        ],
        'threshold': {
            'line': {'color': frammer_text, 'width': 4},
            'thickness': 0.75,
            'value': 1.0
        }
    }
))
fig_gauge.update_layout(height=400)
fig_gauge.show()

"""# **KPI 3 - Mixed Health Index**

This KPI is the Mix Health Index, calculated using Simpson’s Diversity Index.

Mix Health quantifies how balanced your content library is. It identifies whether you are overly dependent on a single content type (a Monoculture) or if you have a healthy, diversified spread across different categories (an Ecosystem).

Formula = (1- sum (p^2))
"""

import plotly.graph_objects as go
import pandas as pd

try:
    # 1. Merge Fact and Dimension to get Names instead of IDs
    # We use a left join to ensure we keep all fact data
    plot_df = pd.merge(fact_input_type, dim_input, on='InputType_ID', how='left')

    # 2. Calculation (Simpson's Diversity)
    # Still calculated on the 'Published Count' values
    def simpson_diversity(counts):
        p = counts / counts.sum()
        return 1 - (p**2).sum()

    diversity_score = simpson_diversity(plot_df['Published Count'])
    health_pct = round(diversity_score * 100, 1)

    # 3. Create the Visual
    fig = go.Figure()

    # Frammer Palette
    colors = ['#F24E5B', '#FF8E94', '#C13C47', '#4D4D4D', '#2D2D2D']

    # 4. Add Traces using 'Input_Type_Name' for labels
    for i, row in plot_df.iterrows():
        category_name = row['Input_Type_Name']
        count_val = row['Published Count']

        fig.add_trace(go.Bar(
            name=str(category_name), # This shows the Name in the legend
            x=[count_val],
            y=["Content Mix"],
            orientation='h',
            marker=dict(color=colors[i % len(colors)], line=dict(color='#0F0F0F', width=2)),
            # Hover shows the Name and the Count
            hovertemplate=f"<b>{category_name}</b><br>{int(count_val)} Clips<extra></extra>"
        ))

    # 5. Add the "Health Score" Header
    fig.add_annotation(
        x=0.5, y=1.35,
        text=f"Mix Health Index: <span style='color:#F24E5B'>{health_pct}%</span>",
        showarrow=False,
        font=dict(size=26, color="white", family="Inter, sans-serif"),
        xref="paper", yref="paper"
    )

    # 6. Styling for the Frammer Dark Mode
    fig.update_layout(
        barmode='stack',
        paper_bgcolor='#0F0F0F',
        plot_bgcolor='#0F0F0F',
        showlegend=True,
        legend=dict(
            orientation="h",
            yanchor="bottom",
            y=-0.6,
            xanchor="center",
            x=0.5,
            font=dict(color="white", size=12)
        ),
        margin=dict(t=100, b=100, l=20, r=20),
        height=320,
        xaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
        yaxis=dict(showgrid=False, zeroline=False, showticklabels=False)
    )

    fig.show()

except Exception as e:
    print(f"Error mapping labels: {e}")

"""# **KPI 4 - Platform Diversity Index**

PDI quantifies the degree of uncertainty or spread in your platform strategy. In a content context, high entropy (PDI) means your brand is an omnichannel powerhouse, spreading content so effectively that your presence is balanced across YouTube, TikTok, LinkedIn, Instagram, etc. Low entropy means you are platform-dependent, likely putting all your eggs in one basket.

Shannon Entropy Formula H = - Sum ( p (log (p)))
"""

# PDI: Platform Diversity Index (Shannon Entropy)
platform_counts = fact_channel_pub.groupby('Platform_ID')['Published_Count'].sum()
pdi = entropy(platform_counts)

import plotly.graph_objects as go
import numpy as np

# Gini Coefficient: Measures concentration/inequality in publishing across channels
def get_gini(x):
    x = np.sort(x)
    n = len(x)
    if n == 0 or np.sum(x) == 0: return 0
    return (n + 1 - 2 * np.sum(np.cumsum(x)) / np.sum(x)) / n

channel_gini = get_gini(fact_channel_pub.groupby('Channel_ID')['Published_Count'].sum().values)

# 1. Prepare Data
df_plot = platform_counts.reset_index().sort_values('Published_Count', ascending=False)
df_plot['cum_percent'] = df_plot['Published_Count'].cumsum() / df_plot['Published_Count'].sum() * 100
df_plot['ideal_line'] = np.linspace(100/len(df_plot), 100, len(df_plot))

# 2. Create the Plot
fig = go.Figure()

# Bars for Volume
fig.add_trace(go.Bar(
    x=df_plot['Platform_ID'],
    y=df_plot['Published_Count'],
    name="Platform Volume",
    marker_color='#636EFA',
    opacity=0.7
))

# Line for Concentration (The Lorenz-style Line)
fig.add_trace(go.Scatter(
    x=df_plot['Platform_ID'],
    y=df_plot['cum_percent'],
    name="Cumulative Share %",
    yaxis="y2",
    line=dict(color='#EF553B', width=4, dash='dot'),
    mode='lines+markers'
))

# 3. Layout & Styling
fig.update_layout(
    title=f"Platform Distribution Analysis (PDI: {pdi:.2f} | Gini: {channel_gini:.2f})",
    xaxis_title="Platforms (Ranked by Volume)",
    yaxis=dict(title="Units Published"),
    yaxis2=dict(title="Cumulative % of Total Reach", overlaying="y", side="right", range=[0, 105]),
    template="plotly_white",
    legend=dict(x=0.01, y=0.99)
)

# KPI 4: Platform Diversity Index
fig = go.Figure()
fig.add_trace(go.Bar(
    x=df_plot['Platform_ID'],
    y=df_plot['Published_Count'],
    name="Platform Volume",
    marker_color=frammer_dark_red,
    opacity=0.9
))
fig.add_trace(go.Scatter(
    x=df_plot['Platform_ID'],
    y=df_plot['cum_percent'],
    name="Cumulative Share %",
    yaxis="y2",
    line=dict(color=frammer_red, width=4, dash='dot'),
    mode='lines+markers'
))
fig.update_layout(
    title=f"Platform Distribution Analysis (PDI: {pdi:.2f} | Gini: {channel_gini:.2f})",
    xaxis_title="Platforms (Ranked by Volume)",
    yaxis=dict(title="Units Published"),
    yaxis2=dict(title="Cumulative % of Total Reach", overlaying="y", side="right", range=[0, 105]),
    legend=dict(x=0.01, y=0.99, bgcolor='rgba(15,15,15,0.8)')
)
fig.show()

"""# **KPI 5 - Gini Impurity**
This KPI is the Gini Coefficient, visualized via the Lorenz Curve. While your previous metrics (Simpson and Shannon) measure diversity and variety, the Gini Coefficient is specifically designed to measure Inequality and Concentration.

The Lorenz Curve (the red line in your plot) maps the cumulative share of content against the cumulative share of channels.
The Line of Perfect Equality: A 45-degree diagonal. If you have 10 channels, each would contribute exactly 10% of the content.
The Lorenz Curve: The actual data. The further it sags away from the diagonal, the higher the inequality.

Formula Logic: The code calculates this by comparing the sum of cumulative totals to a theoretical perfect sum.
"""

# Gini Coefficient: Measures concentration/inequality in publishing across channels
def get_gini(x):
    x = np.sort(x)
    n = len(x)
    if n == 0 or np.sum(x) == 0: return 0
    return (n + 1 - 2 * np.sum(np.cumsum(x)) / np.sum(x)) / n

channel_gini = get_gini(fact_channel_pub.groupby('Channel_ID')['Published_Count'].sum().values)

import numpy as np
import plotly.graph_objects as go

# 1. Prepare data for Lorenz Curve
x = np.sort(fact_channel_pub.groupby('Channel_ID')['Published_Count'].sum().values)
n = len(x)
lorenz_curve = np.cumsum(x) / np.sum(x)
lorenz_curve = np.insert(lorenz_curve, 0, 0) # Start at origin
ideal_line = np.linspace(0, 1, len(lorenz_curve))

# 2. Plotting
fig_gini = go.Figure()

# Line of Perfect Equality
fig_gini.add_trace(go.Scatter(x=ideal_line, y=ideal_line,
                             name='Perfect Equality',
                             line=dict(color='black', dash='dash')))

# Actual Distribution (Lorenz Curve)
fig_gini.add_trace(go.Scatter(x=ideal_line, y=lorenz_curve,
                             fill='tonexty', # Fills the area for the Gini ratio
                             name='Actual Distribution',
                             line=dict(color='firebrick', width=3)))

fig_gini.update_layout(
    title=f"Channel Distribution Inequality (Gini: {channel_gini:.2f})",
    xaxis_title="Cumulative % of Channels",
    yaxis_title="Cumulative % of Published Content",
    template="plotly_white",
    yaxis=dict(range=[0, 1], tickformat=".0%"),
    xaxis=dict(range=[0, 1], tickformat=".0%")
)

fig_gini = go.Figure()
fig_gini.add_trace(go.Scatter(x=ideal_line, y=ideal_line, name='Perfect Equality', line=dict(color='#757575', dash='dash')))
fig_gini.add_trace(go.Scatter(x=ideal_line, y=lorenz_curve, fill='tonexty', name='Actual Distribution', fillcolor='rgba(242, 78, 91, 0.2)', line=dict(color=frammer_red, width=3)))
fig_gini.update_layout(
    title=f"Channel Distribution Inequality (Gini: {channel_gini:.2f})",
    xaxis_title="Cumulative % of Channels", yaxis_title="Cumulative % of Published Content",
    yaxis=dict(range=[0, 1], tickformat=".0%"), xaxis=dict(range=[0, 1], tickformat=".0%")
)
fig_gini.show()

fig_gauge2 = go.Figure(go.Indicator(
    mode = "gauge+number",
    value = channel_gini,
    title = {'text': "Gini Concentration Index", 'font': {'color': frammer_text}},
    gauge = {
        'axis': {'range': [0, 1], 'tickcolor': frammer_text},
        'bar': {'color': frammer_red},
        'bgcolor': frammer_bg,
        'steps': [
            {'range': [0, 0.3], 'color': "#333333"},
            {'range': [0.3, 0.6], 'color': "#555555"},
            {'range': [0.6, 1.0], 'color': frammer_dark_red}
        ],
        'threshold': {'line': {'color': frammer_text, 'width': 4}, 'thickness': 0.75, 'value': 0.5}
    }
))
fig_gauge2.show()

fig_gauge = go.Figure(go.Indicator(
    mode = "gauge+number",
    value = channel_gini,
    title = {'text': "Gini Concentration Index"},
    gauge = {
        'axis': {'range': [0, 1]},
        'bar': {'color': "firebrick"},
        'steps': [
            {'range': [0, 0.3], 'color': "lightgreen"}, # Balanced
            {'range': [0.3, 0.6], 'color': "yellow"},      # Skewed
            {'range': [0.6, 1.0], 'color': "salmon"}    # High Concentration
        ],
        'threshold': {
            'line': {'color': "black", 'width': 4},
            'thickness': 0.75,
            'value': 0.5
        }
    }
))

fig_gauge.show()

"""#**KPI 6: Latency**

Latency measures the speed to market of the content. It calculates the time delta between when a video is finished processing (the "Processed" or "Created" timestamp) and when it is actually live on a platform.

Latency is the gap in time that identifies bottlenecks in your final-mile delivery (approvals, scheduling, or technical delays).

$$\text{Latency} = \text{Timestamp}_{\text{Published}} - \text{Timestamp}_{\text{Processed}}$$
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 1. LATENCY OVER TIME (Monthly Efficiency)
# Description: This KPI measures the average delay between 'Created' and 'Published' states across months. It helps identify if the system is getting slower as volume increases.
# Formula: (Total Published Duration_sec - Total Created Duration_sec) / Total Published

try:
    # Merging monthly facts with month names
    latency_monthly = pd.merge(fact_monthly, dim_month, on='Month_ID', how='left')

    # Calculate Latency in Seconds then convert to Minutes for readability
    # We subtract the time it took to create from the time it was finally published
    latency_monthly['Avg_Latency_Min'] = (
        (latency_monthly['Total Published Duration_sec'] - latency_monthly['Total Created Duration_sec'])
        / latency_monthly['Total Published']
    ) / 60

    plt.figure(figsize=(12, 6))
    sns.lineplot(data=latency_monthly, x='Month_Name', y='Avg_Latency_Min', marker='o', color='teal', linewidth=2.5)
    plt.title('KPI: Monthly Average Publishing Latency', fontsize=14)
    plt.ylabel('Average Latency (Minutes)')
    plt.xlabel('Month')
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.show()
except Exception as e:
    print(f"Error in Monthly Latency: {e}")

# 2. PLATFORM LATENCY (Bottleneck Identification)
# Description: Different platforms (YouTube, Instagram, etc.) have different API speeds or manual review requirements. This KPI identifies which platform is the "slowest" to go live.
# Formula: (Published_Duration - Created_Duration) per Platform

try:
    # We use the Channel/Platform fact table for this
    platform_latency = pd.merge(fact_channel_publishing, dim_platform, on='Platform_ID', how='left')

    # Assuming Published_Duration in this table represents the final timestamp delta
    # If the specific 'Created_Duration' isn't in this table, we analyze the Published_Duration
    # as a proxy for 'Time spent in Publishing Phase'.

    plt.figure(figsize=(10, 6))
    sns.barplot(data=platform_latency, x='Platform_Name', y='Published_Duration', palette='magma', hue='Platform_Name', legend=False)
    plt.title('KPI: Delivery Latency by Platform', fontsize=14)
    plt.ylabel('Total Seconds in Publishing State')
    plt.show()
except Exception as e:
    print(f"Error in Platform Latency: {e}")

# 3. INPUT TYPE VS. LATENCY (Complexity Impact)
# Description: Does the source of the video (e.g., Raw Upload vs. AI Generated) impact how long it takes to publish? This helps determine if certain content types require more review.
# Formula: (Published Duration_sec - Created Duration_sec) grouped by Input Type

try:
    # Merge Input Fact with Input Dimensions
    input_latency = pd.merge(fact_input_type, dim_input, on='InputType_ID', how='left')

    # Calculate Latency (Time between Creation Finish and Publish Finish)
    input_latency['Latency_Sec'] = (
        input_latency['Published Duration (hh:mm:ss)_sec'] - input_latency['Created Duration (hh:mm:ss)_sec']
    )

    plt.figure(figsize=(10, 6))
    # Sorting to show the most latent input types first
    input_latency = input_latency.sort_values('Latency_Sec', ascending=False)
    sns.barplot(data=input_latency, x='Latency_Sec', y='Input_Type_Name', palette='Reds_d', hue='Input_Type_Name', legend=False)
    plt.title('KPI: Latency by Input Content Type', fontsize=14)
    plt.xlabel('Latency (Seconds)')
    plt.show()
except Exception as e:
    print(f"Error in Input Type Latency: {e}")

# 4. LATENCY DISTRIBUTION (The "Consistency" KPI)
# Description: Even if the average is low, a few "stuck" videos can hurt user experience. This plot shows the spread of latency to see if we are consistently fast or highly volatile.

try:
    # Creating a synthetic delta from User Summary to show distribution
    fact_user_summary['Latency_Delta'] = (
        fact_user_summary['Published Duration (hh:mm:ss)_sec'] - fact_user_summary['Created Duration (hh:mm:ss)_sec']
    )

    plt.figure(figsize=(10, 5))
    sns.histplot(fact_user_summary['Latency_Delta'], kde=True, color='purple')
    plt.title('KPI: Latency Distribution (Consistency Check)', fontsize=14)
    plt.xlabel('Seconds Delta (Created to Published)')
    plt.ylabel('Frequency of Videos')
    plt.show()
except Exception as e:
    print(f"Error in Latency Distribution: {e}")

    # 1. LATENCY OVER TIME
try:
    latency_monthly = pd.merge(fact_monthly, dim_month, on='Month_ID', how='left')
    latency_monthly['Avg_Latency_Min'] = ((latency_monthly['Total Published Duration_sec'] - latency_monthly['Total Created Duration_sec']) / latency_monthly['Total Published']) / 60

    plt.figure(figsize=(12, 6))
    sns.lineplot(data=latency_monthly, x='Month_Name', y='Avg_Latency_Min', marker='o', color=frammer_red, linewidth=3)
    plt.title('KPI: Monthly Average Publishing Latency', fontsize=14)
    plt.ylabel('Average Latency (Minutes)')
    plt.xlabel('Month')
    plt.grid(axis='y', linestyle='--', alpha=0.3)
    plt.show()
except Exception as e: print(e)

# 2. PLATFORM LATENCY
try:
    platform_latency = pd.merge(fact_channel_publishing, dim_platform, on='Platform_ID', how='left')
    plt.figure(figsize=(10, 6))
    sns.barplot(data=platform_latency, x='Platform_Name', y='Published_Duration', hue='Platform_Name', legend=False)
    plt.title('KPI: Delivery Latency by Platform', fontsize=14)
    plt.ylabel('Total Seconds in Publishing State')
    plt.show()
except Exception as e: print(e)

# 3. INPUT TYPE VS. LATENCY
try:
    input_latency = pd.merge(fact_input_type, dim_input, on='InputType_ID', how='left')
    input_latency['Latency_Sec'] = (input_latency['Published Duration (hh:mm:ss)_sec'] - input_latency['Created Duration (hh:mm:ss)_sec'])
    plt.figure(figsize=(10, 6))
    input_latency = input_latency.sort_values('Latency_Sec', ascending=False)
    sns.barplot(data=input_latency, x='Latency_Sec', y='Input_Type_Name', hue='Input_Type_Name', legend=False)
    plt.title('KPI: Latency by Input Content Type', fontsize=14)
    plt.xlabel('Latency (Seconds)')
    plt.show()
except Exception as e: print(e)

# 4. LATENCY DISTRIBUTION
try:
    fact_user_summary['Latency_Delta'] = (fact_user_summary['Published Duration (hh:mm:ss)_sec'] - fact_user_summary['Created Duration (hh:mm:ss)_sec'])
    plt.figure(figsize=(10, 5))
    sns.histplot(fact_user_summary['Latency_Delta'], kde=True, color=frammer_red, edgecolor=frammer_bg)
    plt.title('KPI: Latency Distribution (Consistency Check)', fontsize=14)
    plt.xlabel('Seconds Delta (Created to Published)')
    plt.ylabel('Frequency of Videos')
    plt.show()
except Exception as e: print(e)

print("Latency KPI Storyline complete: We explored Time Trends, Platform Bottlenecks, Content Complexity, and Consistency.")

"""# **KPI 7: The Consistency Index**

This code aggregates your data by month to calculate the Coefficient of Variation. We visualize this using a Control Chart style line graph, which shows your "Normal Range" (Mean $\pm$ StdDev).

*The Calculation Logic*

Source: Fact Monthly (for counts) and Dim Month (for labels).

Formula: $CV = \frac{\sigma}{\mu}$ (Standard Deviation of Published Count / Mean of Published Count).

Target: A CV close to 0 is perfect consistency; a CV > 1.0 indicates high volatility.
"""

import pandas as pd
import numpy as np
import plotly.graph_objects as go

# 1. Merge Fact Monthly with Dim Month to get human-readable names
df_consistency = pd.merge(
    fact_monthly,
    dim_month,
    on='Month_ID'
)

# 2. Sort by Month_ID to ensure chronological order in the plot
df_consistency = df_consistency.sort_values('Month_ID')

# 3. Calculate Statistical Components
published_counts = df_consistency['Total Published']
mu = published_counts.mean()
sigma = published_counts.std()
cv_score = sigma / mu if mu != 0 else 0

# 4. Create the Control Chart Visualization
fig_cv = go.Figure()

# Add the "Stability Zone" (Mean +/- 1 StdDev)
fig_cv.add_hrect(
    y0=max(0, mu - sigma),
    y1=mu + sigma,
    fillcolor="rgba(0, 204, 150, 0.1)", # Subtle green
    line_width=0,
    annotation_text="Stability Zone (Normal Range)",
    annotation_position="top left"
)

# Add the Mean Line
fig_cv.add_hline(
    y=mu,
    line_dash="dash",
    line_color="rgba(0, 100, 0, 0.5)",
    annotation_text="Average Production"
)

# Add the Actual Monthly Production Line
fig_cv.add_trace(go.Scatter(
    x=df_consistency['Month_Name'],
    y=published_counts,
    mode='lines+markers+text',
    name="Published Volume",
    text=published_counts,
    textposition="top center",
    line=dict(color='#636EFA', width=4),
    marker=dict(size=10, symbol='diamond')
))

# Styling
fig_cv.update_layout(
    title=f"Production Consistency Analysis (CV: {cv_score:.2f})",
    xaxis_title="Month",
    yaxis_title="Total Published Count",
    template="plotly_white",
    yaxis=dict(range=[0, published_counts.max() * 1.4])
)

fig_cv = go.Figure()

# Add the "Stability Zone" (Mean +/- 1 StdDev)
fig_cv.add_hrect(
    y0=max(0, mu - sigma),
    y1=mu + sigma,
    fillcolor="rgba(242, 78, 91, 0.1)", # Subtle Frammer Red
    line_width=0,
    annotation_text="Stability Zone",
    annotation_position="top left",
    annotation_font_color=frammer_text
)

# Add the Mean Line
fig_cv.add_hline(
    y=mu,
    line_dash="dash",
    line_color="#A3A3A3",
    annotation_text="Average Production",
    annotation_font_color=frammer_text
)

# Add the Actual Monthly Production Line
fig_cv.add_trace(go.Scatter(
    x=df_consistency['Month_Name'],
    y=published_counts,
    mode='lines+markers+text',
    name="Published Volume",
    text=published_counts,
    textposition="top center",
    line=dict(color=frammer_red, width=4),
    marker=dict(size=10, symbol='diamond')
))

fig_cv.update_layout(
    title=f"Production Consistency Analysis (CV: {cv_score:.2f})",
    xaxis_title="Month",
    yaxis_title="Total Published Count",
    yaxis=dict(range=[0, published_counts.max() * 1.4])
)
fig_cv.show()

import plotly.graph_objects as go
import pandas as pd

try:
    # 1. Merge Fact and Dimension for Output Types
    # Adjust 'OutputType_ID' if your column names differ slightly
    output_df = pd.merge(fact_output_type, dim_output, on='OutputType_ID', how='left')

    # 2. Calculation (Simpson's Diversity) for Output
    def simpson_diversity(counts):
        p = counts / counts.sum()
        return 1 - (p**2).sum()

    output_diversity = simpson_diversity(o utput_df['Published Count'])
    output_health_pct = round(output_diversity * 100, 1)

    # 3. Create the Visual
    fig_output = go.Figure()

    # Frammer Palette (Using a slightly different set of shades to distinguish Input vs Output)
    # Coral base, but perhaps adding some deeper reds/grays
    output_colors = ['#F24E5B', '#D13B47', '#A12A34', '#7D7D7D', '#4A4A4A']

    # 4. Add Traces using 'Output_Type_Name'
    for i, row in output_df.iterrows():
        out_name = row['Output_Type_Name']
        out_count = row['Published Count']

        fig_output.add_trace(go.Bar(
            name=str(out_name),
            x=[out_count],
            y=["Output Mix"],
            orientation='h',
            marker=dict(color=output_colors[i % len(output_colors)],
                        line=dict(color='#0F0F0F', width=2)),
            hovertemplate=f"<b>{out_name}</b><br>{int(out_count)} Clips Published<extra></extra>"
        ))

    # 5. Add the "Output Health Score" Header
    fig_output.add_annotation(
        x=0.5, y=1.35,
        text=f"Output Mix Health: <span style='color:#F24E5B'>{output_health_pct}%</span>",
        showarrow=False,
        font=dict(size=26, color="white", family="Inter, sans-serif"),
        xref="paper", yref="paper"
    )

    # 6. Styling (Matching the Input Mix exactly for UI symmetry)
    fig_output.update_layout(
        barmode='stack',
        paper_bgcolor='#0F0F0F',
        plot_bgcolor='#0F0F0F',
        showlegend=True,
        legend=dict(
            orientation="h",
            yanchor="bottom",
            y=-0.6,
            xanchor="center",
            x=0.5,
            font=dict(color="white", size=12)
        ),
        margin=dict(t=100, b=100, l=20, r=20),
        height=320,
        xaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
        yaxis=dict(showgrid=False, zeroline=False, showticklabels=False)
    )

    fig_output.show()

except Exception as e:
    print(f"Error mapping output labels: {e}")